### ISSUE TITLE
EAM-Additional Hard Copy permit

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#10]
@Team,
Customer Format,
![Additional Hardcopy Permit](https://user-images.githubusercontent.com/38855380/108595791-b480ba80-73a7-11eb-9a7e-68625628d71d.jpeg)
@AkashGleen 
we Need clarification from customer

**Comment by eafaisal** [comment]
![1615784979927](https://user-images.githubusercontent.com/65998153/111106531-4630b180-857b-11eb-97b9-301972577314.jpg)
![1615784979932](https://user-images.githubusercontent.com/65998153/111106534-48930b80-857b-11eb-88ea-4e54f2bffd23.jpg)
![1615784979935](https://user-images.githubusercontent.com/65998153/111106539-492ba200-857b-11eb-9c09-a0d9b9ee6231.jpg)
![1615784979938](https://user-images.githubusercontent.com/65998153/111106542-4a5ccf00-857b-11eb-937e-7a8da74788c4.jpg)

**Comment by eafaisal** [comment]
PFS is completed.

[Additional_Hard_Copy_Permit.xlsx](https://github.com/astpl1998/PPN-Power/files/6413872/Additional_Hard_Copy_Permit.xlsx)

**Comment by eafaisal** [comment]
@raju-kurup 

As we discussed the PFS is updated.

[Additional_Hard_Copy_Permit_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6700945/Additional_Hard_Copy_Permit_V1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
As discussed with client the changes are done and highlighted.
Updated PFS: 
[Additional_Hard_Copy_Permit_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6702226/Additional_Hard_Copy_Permit_V1.2.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development as per the PFS attached

**Comment by karthikeyanamitysoft** [comment]
There is no button for report launch, shall i put only that one button for print, is it okay or need any other button ?

![image](https://user-images.githubusercontent.com/40713407/123413544-88cd4580-d5d0-11eb-9d4a-88cbadf1e24a.png)

**Comment by raju-kurup** [comment]
@Senthilmurugan-B : please clarify the karthi query

**Comment by Senthilmurugan-B** [comment]
@karthikeyanamitysoft : 
Pls refer the last Updated PFS in that two buttons are included "Save" "Print"
![image](https://user-images.githubusercontent.com/38855380/123580344-476aaf00-d7f7-11eb-9bf3-ce13114e7112.png)
[Additional_Hard_Copy_Permit_PFS.xlsx](https://github.com/astpl1998/PPN-Power/files/6723395/Additional_Hard_Copy_Permit_PFS.xlsx)

**Comment by Senthilmurugan-B** [comment]
@karthikeyanamitysoft:
Refer the updated PFS.
[Additional_Hard_Copy_Permit_PFS.xlsx](https://github.com/astpl1998/PPN-Power/files/6723408/Additional_Hard_Copy_Permit_PFS.xlsx)

**Comment by eafaisal** [comment]
@karthikeyanamitysoft 

Except main print out,all other additional print outs are removed from PFS.
Updated PFS: 
[Additional_Hard_Copy_Permit.xlsx](https://github.com/astpl1998/PPN-Power/files/6723413/Additional_Hard_Copy_Permit.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@BalaramanM 

As we discussed, the sheet name 'UDS Layout Screen' is changed as 'Screen Layout'.
The Activity Path is updated in Screen Layout sheet.
[Additional_Hard_Copy_Permit_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6747065/Additional_Hard_Copy_Permit_V1.1.xlsx)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Development completed .kindly check and revert
[AMITYUSER__74301032_a211bfbf-dea2-4e16-8249-e6feca8835e5.pdf](https://github.com/astpl1998/PPN-Power/files/6792233/AMITYUSER__74301032_a211bfbf-dea2-4e16-8249-e6feca8835e5.pdf)

Regrads,
Preetha

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

If we give the decimal values in '4. Gas Test' in Safety Checks, it's throwing the error 'Conversion failed when converting the varchar value '10.5' to data type int.'
Also if we give whole numbers 'Gas Test' values are not printed.
Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Above mentioned issues are cleared
kindly check.
Regards,
preetha

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

1. In print out, the following values are wrong.
I. ERP PERMIT No
II. LOB No
III. Date and time
2. In time field, the date is printed wrongly.
3. Job Description is not fetched

Kindly check in attached print out.
[ACP.pdf](https://github.com/astpl1998/PPN-Power/files/6891859/ACP.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned corrections are done.
kindly check.
Regards,
Preetha
[additional_hardcopy.pdf](https://github.com/astpl1998/PPN-Power/files/6899389/additional_hardcopy.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

In print out the following issues were found.
1. LOB No is wrong
2. The "No of persons working in confined space" was not printed.
[ACP.pdf](https://github.com/astpl1998/PPN-Power/files/6910934/ACP.pdf)

Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The mentioned issues are resolved.
kindly check.
Regards,
preetha
[acd1.pdf](https://github.com/astpl1998/PPN-Power/files/6923470/acd1.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

In EXCAVATION PERMIT,the line '**MMD-   EMD-   C&I-   Civil**  ' is missing.
The border needs to be aligned properly.
Kindly check.

[ACP.pdf](https://github.com/astpl1998/PPN-Power/files/6923679/ACP.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issuses are resolved.
kindly check
Regards,
preetha
[additional_hardcopy_permit.pdf](https://github.com/astpl1998/PPN-Power/files/6924344/additional_hardcopy_permit.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

1. The logic for Permit Type field in header is changed
2. In EXCAVATION PERMIT,for the line 'MMD- EMD- C&I- Civil check box is added.
PFS is updated.

[Additional_Hard_Copy_Permit_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6952407/Additional_Hard_Copy_Permit_V1.1.xlsx)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned changes are done.
kindly check.
Regards,
preetha
[acd14821.pdf](https://github.com/astpl1998/PPN-Power/files/6986242/acd14821.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

The following corrections are needed in print.
1. By mistake,date is coming in time field also.It should be removed.
2. In footer 'Permit Received by' is missing.
3. The sentences with bold and underline should be same like as PFS.
[addnl_cp.pdf](https://github.com/astpl1998/PPN-Power/files/6992207/addnl_cp.pdf)

Kindy check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are resolved.
kindly check.
Regards,
preetha
[a_c_d17821.pdf](https://github.com/astpl1998/PPN-Power/files/6997519/a_c_d17821.pdf)

**Comment by eafaisal** [comment]
Testing 1 is completed.

Test Case: [Testing1_Test_Case_Additional_Hard_Copy_permit.xlsx](https://github.com/astpl1998/PPN-Power/files/7004636/Testing1_Test_Case_Additional_Hard_Copy_permit.xlsx)
Test Result: [Testing1_Test_Result_Additional_Hard_Copy_permit.pdf](https://github.com/astpl1998/PPN-Power/files/7004640/Testing1_Test_Result_Additional_Hard_Copy_permit.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@viki18790 

Kindly start the testing 2.

Regards,
Faisal

**Comment by viki18790** [comment]
@eafaisal 

Testing 2 completed. Please find attached the Test Case and Test Result for EAM-Additional Hard Copy Permit

Regards, 

Viignesh 
[Testing2_Test Result_Additional_Hard Copy_ Permit.pdf](https://github.com/astpl1998/PPN-Power/files/7038109/Testing2_Test.Result_Additional_Hard.Copy_.Permit.pdf)
[Testing2_Test_Case_Additional_Hard_Copy_permit.xlsx](https://github.com/astpl1998/PPN-Power/files/7038110/Testing2_Test_Case_Additional_Hard_Copy_permit.xlsx)

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned corrections are done.
kindly check.
Regards,
preetha
[ACD3921.pdf](https://github.com/astpl1998/PPN-Power/files/7106031/ACD3921.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

Job description is not fully printed.
Kindly check.
[WAH.CS.HW.pdf](https://github.com/astpl1998/PPN-Power/files/7109293/WAH.CS.HW.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above corrections are done.
kindly check.
Regards,
preetha
[wah_cs_hw.pdf](https://github.com/astpl1998/PPN-Power/files/7109335/wah_cs_hw.pdf)

**Comment by eafaisal** [comment]
Testing is completed.
[Testing2.Test.Result.additional.hard.copy.permit.pdf](https://github.com/astpl1998/PPN-Power/files/7109346/Testing2.Test.Result.additional.hard.copy.permit.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The client has requested the following changes in report.
1. **Valid from date** and **to date**,**valid from time** and **to time** should be fetched from **Maintain Additional Clearance Permit** screen
2. The space for **Job Description** field needs to be increased.
3. The font size and space alignments need to be done as marked in print out. (Please refer attached print out received from client)

![ACP_Corrections](https://user-images.githubusercontent.com/65998153/133412263-839e7c61-ff86-4e0a-8551-14fa04abcc51.jpg)

Updated PFS: [Additional_Hard_Copy_Permit_V1.4.xlsx](https://github.com/astpl1998/PPN-Power/files/7168988/Additional_Hard_Copy_Permit_V1.4.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup SIr,

As discussed with Mr.Solomon from PPN,he agreed to give **OK** instead of tick mark in all check boxes.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed earlier regarding this report, we want to do the customer requirement. Instead of a tick mark, the customer agreed to put OK and page alignment in the bottom also to be attended to.  Contact Faisal for any clarification

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned corrections are done.
kindly check.
Regards,
preetha
[prmit.pdf](https://github.com/astpl1998/PPN-Power/files/7243133/prmit.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

Still between the sentences, double lines are coming in print.
It needs to removed.
[Testing2_Test_Result_Addnl.Hard.Copy.Permit.pdf](https://github.com/astpl1998/PPN-Power/files/7249201/Testing2_Test_Result_Addnl.Hard.Copy.Permit.pdf)

Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are cleared.
kindly check.
Regards,
preetha
[addpermit.pdf](https://github.com/astpl1998/PPN-Power/files/7250338/addpermit.pdf)

**Comment by eafaisal** [comment]
Testing is completed
[Additional_Hard_Copy_Permit.pdf](https://github.com/astpl1998/PPN-Power/files/7250742/Additional_Hard_Copy_Permit.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The client has requested few more changes.
1. The word _'vessel entry'_ is to be removed from point 1 in excavation permit.
2. The sentence _'Obtain clearance permit from existing additional permit holder in same work area'
MMD-              EMD-              C&I-             Civil-            Operation-'_ to be added in confined space permit as point 8.
3. The remaining space below the permit types is be added in **Remarks** field. 
4. The spaces at right and left sides are to be removed.

(Customer print out is attached)
![IMG_20210930_170013](https://user-images.githubusercontent.com/65998153/135569848-27460033-929e-47bb-9581-ad579ce7cb86.jpg)

The points are updated in PFS.
[Additional_Hard_Copy_Permit_V1.5.xlsx](https://github.com/astpl1998/PPN-Power/files/7264334/Additional_Hard_Copy_Permit_V1.5.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in this report.
1. remove of that word
2. 2 lines to be added
3. Remarks column more space
4. print out can be expanded more.

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per client's request the logic for _Permit Type_ in header needs to be changed.
Kindly move to developement.
Updated PFS: [Additional_Hard_Copy_Permit_V1.6.xlsx](https://github.com/astpl1998/PPN-Power/files/7445891/Additional_Hard_Copy_Permit_V1.6.xlsx)
 
Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : only 1 change (ie) in header permit type as per the PFS attached

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

Kindly do the change as mentioned.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The mentioned changes are done.
 kindly check.
Regards,
preetha
[Permitcopy.pdf](https://github.com/astpl1998/PPN-Power/files/7531660/Permitcopy.pdf)

**Comment by eafaisal** [comment]
Testing is completed.
[Additional.Clearance.Permit.pdf](https://github.com/astpl1998/PPN-Power/files/7531846/Additional.Clearance.Permit.pdf)

**Comment by PreethaGopalakrishnan** [comment]
[newdeliverables.zip](https://github.com/astpl1998/PPN-Power/files/7538381/newdeliverables.zip)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer has agreed this report.
![image](https://user-images.githubusercontent.com/65998153/142565359-9f09eb50-d538-44c4-9f3f-eea7ba281f51.png)

Kindly move this to deploy in live server.
PFS: [Additional_Hard_Copy_Permit_V1.6 (2).xlsx](https://github.com/astpl1998/PPN-Power/files/7567754/Additional_Hard_Copy_Permit_V1.6.2.xlsx)
 Latest Deliverables: [newdeliverables (1).zip](https://github.com/astpl1998/PPN-Power/files/7567756/newdeliverables.1.zip)
 Test Case 1: [Testing1_Test_Case_Additional_Hard_Copy_permit.xlsx](https://github.com/astpl1998/PPN-Power/files/7567759/Testing1_Test_Case_Additional_Hard_Copy_permit.xlsx)
 Test Result 1: [Testing1_Test_Result_Additional_Hard_Copy_permit.pdf](https://github.com/astpl1998/PPN-Power/files/7567760/Testing1_Test_Result_Additional_Hard_Copy_permit.pdf)
 Test Case 2: [Testing2_Test_Case_Additional_Hard_Copy_permit.xlsx](https://github.com/astpl1998/PPN-Power/files/7567761/Testing2_Test_Case_Additional_Hard_Copy_permit.xlsx)
 Test Result 2: [Testing2_Test.Result_Additional_Hard.Copy_.Permit.pdf](https://github.com/astpl1998/PPN-Power/files/7567762/Testing2_Test.Result_Additional_Hard.Copy_.Permit.pdf)
 
Regards,
Faisal

**Comment by raju-kurup** [comment]
Testing completed by us and PPN accepted, so please move this development to Live server

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Deployed in live server.
kindly check.
Regards,
preetha.
![Screenshot (533)](https://user-images.githubusercontent.com/85933899/142830984-a0491dd2-6f5a-42b2-9f6e-e38bc72cd716.png)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Being development completed and deployed in live, we are closing this ticket.
