### ISSUE TITLE
EAM-Work Order MRQ print

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#11]
@team,
Customer Format,
![WO MRQ Print Out](https://user-images.githubusercontent.com/38855380/108596040-6e782680-73a8-11eb-9629-d5c35bd4973f.jpeg)
@AkashGleen,
KIndly start the PFS

**Comment by AkashGleen** [comment]
Dear Senthilmurugan

EAM-Work Order MRQ print PFS as been Completed Kindly Check & Update.

[Wo_MRQ PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6019836/Wo_MRQ.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
Dear Raju Sir,

EAM-Work Order MRQ print PFS as been Completed. Kindly Start With Review

[Wo_MRQ PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6036182/Wo_MRQ.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@Senthilmurugan-B : As discussed, please do the correction

**Comment by Senthilmurugan-B** [comment]
@akash ; as discussed with raju sir, kindly remove the formula in Qty issued (no.14) make as a user defined field

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

As discussed, correction as been Done Kindly Move Next Level

[Wo_MRQ.PFS.v1.0 (2).xlsx](https://github.com/astpl1998/PPN-Power/files/6374698/Wo_MRQ.PFS.v1.0.2.xlsx)

Regards,
Akash

**Comment by Senthilmurugan-B** [comment]
@karthikeyanamitysoft 
Kindly assign to the developer this is one of the high priority report

**Comment by karthikeyanamitysoft** [comment]
Already Jeyapriya completed  the report, only data trasfer issue only exist.

**Comment by Narendiranath** [comment]
Hi Akash,

           Development is completed. Kindly check and revert back. PFA Latest deliverables & Test result for your ref. 

[WO - Material Requestion.pdf](https://github.com/astpl1998/PPN-Power/files/6522161/WO.-.Material.Requestion.pdf)

[PPNE-81.zip](https://github.com/astpl1998/PPN-Power/files/6522163/PPNE-81.zip)

Regards,
Naren

**Comment by Senthilmurugan-B** [comment]
@eafaisal,
KIndly allocate this report to vignesh for testing 1

**Comment by eafaisal** [comment]
@viki18790 

Kindly start the testing 1

Regards,
Faisal

**Comment by viki18790** [comment]
@eafaisal 

I have completed testing 1, please verify. I have also attached the test case along with the maintenance issue
[AMITYUSER__EAM WO MRQ.pdf](https://github.com/astpl1998/PPN-Power/files/6526402/AMITYUSER__EAM.WO.MRQ.pdf)
[Maintenance Issue.pdf](https://github.com/astpl1998/PPN-Power/files/6526403/Maintenance.Issue.pdf)
[Testing1_Test_Case_WO_Material.Requisition.xlsx](https://github.com/astpl1998/PPN-Power/files/6526404/Testing1_Test_Case_WO_Material.Requisition.xlsx)




Regards, 
Faisal

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_WOMRQ.xlsx](https://github.com/astpl1998/PPN-Power/files/6527602/Testing2_Test_Case_WOMRQ.xlsx)
Test Result: [Testing2_Test_Result_WOMRQ.pdf](https://github.com/astpl1998/PPN-Power/files/6527603/Testing2_Test_Result_WOMRQ.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
The spelling mistakes in 'Material Requisition' in header and 'Available Quantity' are corrected in PFS.

[Wo_MRQ.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6529970/Wo_MRQ.PFS.v1.1.xlsx)

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir:
client has given Confirmation Kindly check and moved to Live server
PFS : [Wo_MRQ.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6564293/Wo_MRQ.PFS.v1.1.xlsx)
Latest Deliverables : [PPNE-81.zip](https://github.com/astpl1998/PPN-Power/files/6564300/PPNE-81.zip)
Testing_1 Test Case : [Testing1_Test_Case_WO_Material.Requisition.xlsx](https://github.com/astpl1998/PPN-Power/files/6564319/Testing1_Test_Case_WO_Material.Requisition.xlsx)
Testing_1 Result : [Testing1_Test Result_EAM.WO.MRQ.pdf](https://github.com/astpl1998/PPN-Power/files/6564411/Testing1_Test.Result_EAM.WO.MRQ.pdf)
Testing_2 Test case : [Testing2_Test_Case_WOMRQ.xlsx](https://github.com/astpl1998/PPN-Power/files/6564414/Testing2_Test_Case_WOMRQ.xlsx)
Testing_2 Test Result : [Testing2_Test_Result_WOMRQ.pdf](https://github.com/astpl1998/PPN-Power/files/6564444/Testing2_Test_Result_WOMRQ.pdf)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Move this development from UAT server to live server

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Kinldy mvoe the deliverablse into live server and attach the complete deliverables with ER file

**Comment by Narendiranath** [comment]
@karthikeyanamitysoft 

            Deliverables deployed in live server. But when click UDS Screen in live server Exception error thrown. Ramco is looking on that issue. So this report i put it on Hold.

Regards,
Naren

**Comment by Narendiranath** [comment]
Hi,

PFA Latest Deliverables for your ref.

[PPNE-81.zip](https://github.com/astpl1998/PPN-Power/files/6758249/PPNE-81.zip)
[ER Design.zip](https://github.com/astpl1998/PPN-Power/files/6758251/ER.Design.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Development and deployment completed, so closing this ticket.

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per customer's requirement,the following changes need to be done.
1. The length for the field **'WO Description'** is to be increased to max 150 char.
2. The logic for **'Qty Reqd'** is changed.

PFS  is updated.
[Wo_MRQ.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7133753/Wo_MRQ.PFS.v1.2.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft :

As per customer's requirement, the following changes need to be done.

1. The length for the field 'WO Description' is to be increased to max 150 char.
2. The logic for 'Qty Reqd' is changed. (Previously Reserved Qty taken now Schedule Qty to be taken)

**Comment by Narendiranath** [comment]
Hi Faisal,

            Above mentioned changes are done in both UAT & Live. Kindly check. PFA Latest Deliverables for your ref.

[Deliverable V.4.zip](https://github.com/astpl1998/PPN-Power/files/7161986/Deliverable.V.4.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
Testing is completed.
[Testing2_Test_Result_WOMRQ.pdf](https://github.com/astpl1998/PPN-Power/files/7166819/Testing2_Test_Result_WOMRQ.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
