### ISSUE TITLE
EAM-Calibration Certificate Print (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#12]
@Team,
Customer Format,
![Calibration Certificate Print](https://user-images.githubusercontent.com/38855380/108596132-11c93b80-73a9-11eb-8f86-63d15619c0f1.jpeg)

**Comment by Senthilmurugan-B** [comment]
@Team: 
Report not available  in final customization list.

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
