### ISSUE TITLE
EAM- From and To date Validation In Clearance Permit Transaction (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#14]
@AkashGleen,
Before start PFS, kindly take KT form me

**Comment by Senthilmurugan-B** [comment]
@eafaisal 
As we discussed kindly start the PFS

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The PFS is completed.KIndly move to next level.

[CP_Validation_PFS_1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6568108/CP_Validation_PFS_1.0.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : UDS screen to be developed and the days mentioned in UDS to be taken for validation of Clearance permit creation.

**Comment by Senthilmurugan-B** [comment]
@team: 
asper the PPN mail received from 31/05/2021 with the attachment of the Consolidated Open points list , PPN added comments as " The valid from to date should not exceed 15 days. And the days also should be user-defined - This has been discussed and decided to defer the requirement. "

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
