### ISSUE TITLE
EAM-Store Return Voucher 

### ISSUE THREAD

**Issue by eafaisal** [astpl1998/PPN-Power#17]
@AkashGleen ,
As we discussed Kindly start the PFS.

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Store Return Voucher PFS as been Completed. Kindly Move on Nxt Level

[Store Return Voucher PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6066137/Store.Return.Voucher.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
