### ISSUE TITLE
P&S-Material Inward Note(MIN) Transaction screen

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#18]
@AkashGleen 
Kindly start the PFS as per ref Email.

**Comment by AkashGleen** [comment]
Dear Raju Sir 

Material Inward Note(MIN) Transaction Screen PFS Completed.

[MIN PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6139260/MIN.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

MIN PFS Changes as be Done. Kindly Check & Move on Next Level

[MIN.PFS.v1.0 (1).xlsx](https://github.com/astpl1998/PPN-Power/files/6348491/MIN.PFS.v1.0.1.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report, this is available in first priority

**Comment by mohanaamity** [comment]
@eafaisal ,

EDK design completed. Ticket id: PPNE-77

Regards,
Mohana B

**Comment by BalaramanM** [comment]
@eafaisal 

Development completed.Kindly check and revert back

[PPNE-77.zip](https://github.com/astpl1998/PPN-Power/files/6520861/PPNE-77.zip)

**Comment by eafaisal** [comment]
@BalaramanM 

As we discussed,the MIN transaction number should have 6 digits and increment the numbering for new transactions.
Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
the error resolved now.Kindly check and revert back

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly start the testing 1

Regards,
Faisal

**Comment by eafaisal** [comment]
@BalaramanM 

Edit button is working.After editing the value is not updated.
Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
the error resolved now.kindly check

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the retest

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 has been Completed
[MIN_Test cases.xlsx](https://github.com/astpl1998/PPN-Power/files/6527563/MIN_Test.cases.xlsx)
![MIN_Test result_1](https://user-images.githubusercontent.com/81737937/119249142-fd692a80-bbb3-11eb-9a01-e7d0e23e484f.png)
![MIN_Test result_2](https://user-images.githubusercontent.com/81737937/119249155-05c16580-bbb4-11eb-8934-14d9f749029c.png)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing.2_Test_Case_MIN.pdf.xlsx](https://github.com/astpl1998/PPN-Power/files/6527634/Testing.2_Test_Case_MIN.pdf.xlsx)
Test Result: [Testing.2_Test_Result_MIN.pdf.docx](https://github.com/astpl1998/PPN-Power/files/6527635/Testing.2_Test_Result_MIN.pdf.docx)

Regards,
Faisal

**Comment by eafaisal** [comment]
The spelling is corrected in 'Vehicle No' field in PFS.

[MIN.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6529892/MIN.PFS.v1.1.xlsx)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The customer requested two changes in MIN
1. The Entry Date is to be added in MIN transaction screen
2. The UDS is to be added in GRIN screen to fetch the MIN details for reference.
The PFS is updated.
[MIN.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6961017/MIN.PFS.v1.2.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Through mail it was informed to PPN that it was not possible to populate the data from MIN transaction screen in to GRIN screen as GRIN screen was base screen.

![image](https://user-images.githubusercontent.com/65998153/131303431-1e539d6f-54ac-498f-a8ff-50aec23fce6d.png)

Also the samething was conveyed to Mr. Vadivel Rajan and Mr. Vivek in PPN through phone call on 27.08.2021.
So you can close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Being this requirement cannot be taken and communicated to PPN, so closing this ticket

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The customer agreed to deploy this report in live server through phone call on 03.09.2021
PFS: [MIN.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7105474/MIN.PFS.v1.2.xlsx)
Latest Deliverables: [PPNE-77.zip](https://github.com/astpl1998/PPN-Power/files/7105479/PPNE-77.zip)
Test Case 1: [Testing1_Test_Case_MIN.xlsx](https://github.com/astpl1998/PPN-Power/files/7105487/Testing1_Test_Case_MIN.xlsx)
Test Result 1: [Testing1_Test_Result_MIN .docx](https://github.com/astpl1998/PPN-Power/files/7105488/Testing1_Test_Result_MIN.docx)
Test Case 2: [Testing2_Test_Case_MIN.xlsx](https://github.com/astpl1998/PPN-Power/files/7105491/Testing2_Test_Case_MIN.xlsx)
Test Result 2: [Testing2_Test_Result_MIN.docx](https://github.com/astpl1998/PPN-Power/files/7105495/Testing2_Test_Result_MIN.docx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server and please attach the deployed deliverables in this github.

**Comment by BalaramanM** [comment]
@eafaisal Bro,
Development deployed in live server.Kindly check and confirm.Pls find the below attached Latest deliverables
[MIN screen.zip](https://github.com/astpl1998/PPN-Power/files/7134372/MIN.screen.zip)

Reagards,
Balaraman M

**Comment by eafaisal** [comment]
@raju-kurup SIr,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
