### ISSUE TITLE
P&S-PO Register Dcube report (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#19]
@eafaisal 
As per the customer requirement we need deploy the PO register from other project
need include coloumn
1.cc from PR
2.RFQ against the PR
3.Quotation against the PR

**Comment by Senthilmurugan-B** [comment]
@Team
PPN will develop the report

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
