### ISSUE TITLE
P&S-Recommendation of PO approval

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#2]
@Team,
Customer Format
![PO Recommendation for Approval_customer format](https://user-images.githubusercontent.com/38855380/108483531-da7f5f80-72c0-11eb-9149-552f37f45f7c.jpeg)

**Comment by Senthilmurugan-B** [comment]
@eafaisal 
Kindly start the PFS

**Comment by eafaisal** [comment]
[Recommendation_For_Approval.xlsx](https://github.com/astpl1998/PPN-Power/files/6033467/Recommendation_For_Approval.xlsx)

**Comment by eafaisal** [comment]
Sir,

PFS is completed.It needs to be received.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@KARTHI : Please develop this ticket

**Comment by mohanaamity** [comment]
@eafaisal 

As we discussed , PFS test data(po number) not available in the given path. Kindly provide the test data.
Regards,
Mohana B

**Comment by eafaisal** [comment]
Report is not printed. PPNE-59 RTRACK raised.

**Comment by Senthilmurugan-B** [comment]
@eafaisal : kindly start the Testing 1

**Comment by eafaisal** [comment]
@mohanaamity 

The text entered in fields are not coming fully in print.
Kindly check.

Regards,
Faisal

**Comment by mohanaamity** [comment]
@eafaisal ,

Kindly find the test data FYR.
[AMITYUSER__74301003_c2cb5f6e-cbdd-4e44-8914-ca3a0cb53103.pdf](https://github.com/astpl1998/PPN-Power/files/6413881/AMITYUSER__74301003_c2cb5f6e-cbdd-4e44-8914-ca3a0cb53103.pdf)
Regars,
Mohana B

**Comment by eafaisal** [comment]
Testing 1 is completed by Jestin

Test Case: [Testing 1_TestCase_Recommendation of PO approval.xlsx](https://github.com/astpl1998/PPN-Power/files/6440746/Testing.1_TestCase_Recommendation.of.PO.approval.xlsx)
Test Result: [Testing 1_Test_Result_Recommendation of PO approval.pdf](https://github.com/astpl1998/PPN-Power/files/6440751/Testing.1_Test_Result_Recommendation.of.PO.approval.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
I have completed the testing 2.

Test Case: [Testing 2_TestCase_Recommendation of PO approval.xlsx](https://github.com/astpl1998/PPN-Power/files/6445255/Testing.2_TestCase_Recommendation.of.PO.approval.xlsx)
Test Result: [Testing 2_Test_Result_Recommendation of PO approval.pdf](https://github.com/astpl1998/PPN-Power/files/6445257/Testing.2_Test_Result_Recommendation.of.PO.approval.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@mohanaamity 

The client needs the following changes,
1.The data entered in the 'Indentor' and 'Need' fields are interchanged.It should be corrected.
2.The 'Total Value Landed' field should be editable
3.The 'Remarks' field alingment needs to be corrected.
4.The line below 'Remarks' field is not required
5.More spaces are required for Signatories
6.The data once entered in the UDS should be saved and accessible at any time.

The changes are updated in PFS

[Recommendation_For_Approval_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6464165/Recommendation_For_Approval_V1.1.xlsx)


Kindly check.

**Comment by mohanaamity** [comment]
@eafaisal ,

As per PFS requirement, Po value landed column added in uds screen. Ticket Id - PPNE-80

Regards,
Mohana B

**Comment by mohanaamity** [comment]
@eafaisal ,

Report changes completed. I have attached test data FYR. Kindly check and confirm.
[AMITYUSER__74301003_2c879f62-6d9c-48fe-9293-37326cd23a3a.pdf](https://github.com/astpl1998/PPN-Power/files/6515293/AMITYUSER__74301003_2c879f62-6d9c-48fe-9293-37326cd23a3a.pdf)

Regards,
Mohana B

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@mohanaamity 

The data entered in UDS fields are saved and printed correctly.
But again if we do the on enter, the data what we fed are not fetched.
Kindly check.

Regards,
Faisal

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly start the testing 1

Regards,
Faisal

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 Completed

[Recommendation of PO approval_test cases.xlsx](https://github.com/astpl1998/PPN-Power/files/6525835/Recommendation.of.PO.approval_test.cases.xlsx)
[Uploading Recommendation_For_Approval_test result 1.pdf…]()

**Comment by eafaisal** [comment]
@mohanaamity 

After editing the Total Value landed field,while saving the new value,it is vanished.
Also while doing the on enter next time,it fetches the old value,not edited value.

Kindly check.

Regards,
Faisal

**Comment by mohanaamity** [comment]
@eafaisal 

Issue has been resolved .

Regards,
Mohana B

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing 2_TestCase_Recommendation of PO approval.xlsx](https://github.com/astpl1998/PPN-Power/files/6526449/Testing.2_TestCase_Recommendation.of.PO.approval.xlsx)
Test Result: 
[Testing 2_Test_Result_Recommendation of PO approval.pdf](https://github.com/astpl1998/PPN-Power/files/6526450/Testing.2_Test_Result_Recommendation.of.PO.approval.pdf)

Regards,
Faisal

**Comment by mohanaamity** [comment]
@eafaisal 

Latest Deliverable Attached FYR.
[Latest Deliverable.zip](https://github.com/astpl1998/PPN-Power/files/6538313/Latest.Deliverable.zip)
Rgards,
Mohana B

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir:
client has given Confirmation for this report,
Kindly check and moved to Live server
PFS : [PFS_Recommendation_For_Approval_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6567634/PFS_Recommendation_For_Approval_V1.1.xlsx)
Latest Deliverables : [Latest.Deliverable.zip](https://github.com/astpl1998/PPN-Power/files/6567635/Latest.Deliverable.zip)
Testing_1 Test Case : [Testing_1 Test Case_Recommendation.of.PO.approval_test.cases.xlsx](https://github.com/astpl1998/PPN-Power/files/6567637/Testing_1.Test.Case_Recommendation.of.PO.approval_test.cases.xlsx)
Testing_1 Result : [Testing 1 Result for Reccomdation of PO Approval.pdf](https://github.com/astpl1998/PPN-Power/files/6567645/Testing.1.Result.for.Reccomdation.of.PO.Approval.pdf)
Testing_2 Test case : [Testing.2_TestCase_Recommendation.of.PO.approval.xlsx](https://github.com/astpl1998/PPN-Power/files/6567646/Testing.2_TestCase_Recommendation.of.PO.approval.xlsx)
Testing_2 Test Result : [Testing.2_Test_Result_Recommendation.of.PO.approval.pdf](https://github.com/astpl1998/PPN-Power/files/6567648/Testing.2_Test_Result_Recommendation.of.PO.approval.pdf)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Move this development from UAT server to live server

**Comment by karthikeyanamitysoft** [comment]
Dear Mohana,

Kindly move the deliverables into live server and attach the complete deliverables with ER file

Regards,
Karthi

**Comment by mohanaamity** [comment]
@Senthilmurugan-B 

PPN live server deployment completed.
[PPNE-80.zip](https://github.com/astpl1998/PPN-Power/files/6856820/PPNE-80.zip)

Regards,
Mohana B

**Comment by eafaisal** [comment]
@mohanaamity 

In live server after saving the fields and if client does on enter in Ref No field,the error "Arithmetic overflow error converting nvarchar to data type numeric" is thrown.
PO No: PPO/000050/21-22
Kindly check.

Regards,
Faisal

**Comment by eafaisal** [comment]
@mohanaamity 

When client takes print our,this error is thrown.

![rfa](https://user-images.githubusercontent.com/65998153/127628697-eb59004f-080a-46f4-b668-7540c3b049e5.png)

Regards,
Faisal

**Comment by eafaisal** [comment]
@mohanaamity 

In this screen the **Total Value Landed** was fetched from PO.
The remaining fields were entered manually.
While printing the error is thrown.

![RFA](https://user-images.githubusercontent.com/65998153/128157447-481a8bde-667e-439f-bda1-3f00a921c84a.png)

Kindly check.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per client's requirement,this report is reqired for Amended PO also.
So this is to be deployed in the path :  **Purchase and Subcontracting--> Purchase Order--> Amend Purchase Order**
The PFS is updated.
[PFS_Recommendation_For_Approval_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7029270/PFS_Recommendation_For_Approval_V1.2.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Already UDS is provided to feed data manually in Edit PO screen. Now customer has a chance to Amend the PO that time they want to change the UDS data also.  So we want to keep the UDS in Amend screen and data should flow from Edit screen UDS and changes to be done and Save & take print.

**Comment by eafaisal** [comment]
@mohanaamity 

After editing the **Total Value Landed** field it's printed.
But it's not saved.
Suppose if client goes and does on enter in that PO, it's fetching the old PO value.
Kindly check the issue.
(Ref PO: PPO/000094/21-22)

Regards,
Faisal

**Comment by eafaisal** [comment]
@mohanaamity 

If the PO value is edited or amended it's not fetched to the **Total Value Landed** field in UDS.
In UDS it's showing the old value.

Kindly check.

Regards,
Faisal

**Comment by mohanaamity** [comment]
@eafaisal 

Report has been completed. Kindly check and completed.

Regards,
Mohana B

**Comment by eafaisal** [comment]
Testing is completed.
[Testing.2_Test_Result_Recommendation.of.PO.approval.pdf](https://github.com/astpl1998/PPN-Power/files/7264175/Testing.2_Test_Result_Recommendation.of.PO.approval.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment is completed and accepted by the client through email.

![image](https://user-images.githubusercontent.com/65998153/141102388-bb9a4eee-bb17-4d65-8c07-4c6da2dad913.png)

Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
PPN Accepted and moved to live server, so closing this issue
