### ISSUE TITLE
I&P- Material Request print

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#22]
@AkashGleen,
Kindly start the PFS,
we have a hard copy kindly attach the image.

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

Material Request Print PFS as been Completed. Kindly Move On Next Level

[MR Print PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6363277/MR.Print.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by Senthilmurugan-B** [comment]
@karthikeyanamitysoft 
Kindly assign to the developer, this is one of the high priority report

**Comment by Senthilmurugan-B** [comment]
@efaisal : 
Kindly check with srini and identify the resource and assign for testing 1

**Comment by Nandhineedevi** [comment]
Completed. Kindly check and revert back.

[mr print.pdf](https://github.com/astpl1998/PPN-Power/files/6456967/mr.print.pdf)
[mrqprint_v1.2.zip](https://github.com/astpl1998/PPN-Power/files/6456969/mrqprint_v1.2.zip)

**Comment by eafaisal** [comment]
@Nandhineedevi 

The warehouse details are dublicate for item 2 and 4.
Please check the print out.

[MR_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6507458/MR_Print.pdf)

Regards,
Faisal

**Comment by Nandhineedevi** [comment]
Completed.

[MR_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6509974/MR_Print.pdf)
[mrqprint_v1.3.zip](https://github.com/astpl1998/PPN-Power/files/6509979/mrqprint_v1.3.zip)

**Comment by Senthilmurugan-B** [comment]
@venkatvikram :
KIndly update the Testing 1 test case and result..

**Comment by venkatvikram** [comment]
Testing 1 test case: Testing 1_ test case _

Material Request print
[Material Request print.xlsx](https://github.com/astpl1998/PPN-Power/files/6512927/Material.Request.print.xlsx)

Testing 1 test Result : Testing 1_ test result_ Material Request print
[Material Request print.pdf](https://github.com/astpl1998/PPN-Power/files/6512929/Material.Request.print.pdf)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_Material_Request_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6513220/Testing2_Test_Case_Material_Request_Print.xlsx)

Test Result: [Testing2_Test_Result_Material_Request_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6513221/Testing2_Test_Result_Material_Request_Print.pdf)

Regards,
Faisal

**Comment by Nandhineedevi** [comment]
Latest Deliverable attached for your reference.

[Import File.zip](https://github.com/astpl1998/PPN-Power/files/6564257/Import.File.zip)

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir:
client has given Confirmation for this report,
Kindly check and moved to Live server
PFS:[MR.Print.PFS.v1.1 (1).xlsx](https://github.com/astpl1998/PPN-Power/files/6564454/MR.Print.PFS.v1.1.1.xlsx)
Latest Deliverables : [Import.File.zip](https://github.com/astpl1998/PPN-Power/files/6564457/Import.File.zip)
Testing_1 Test Case : [Testing_1 Test case Material.Request.print.xlsx](https://github.com/astpl1998/PPN-Power/files/6564463/Testing_1.Test.case.Material.Request.print.xlsx)
Testing_1 Result : [Testing_1 Test Result Material.Request.print.pdf](https://github.com/astpl1998/PPN-Power/files/6564464/Testing_1.Test.Result.Material.Request.print.pdf)
Testing_2 Test case : [Testing2_Test_Case_Material_Request_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6564471/Testing2_Test_Case_Material_Request_Print.xlsx)
Testing_2 Test Result : [Testing2_Test_Result_Material_Request_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6564473/Testing2_Test_Result_Material_Request_Print.pdf)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Move this development from UAT server to live server

**Comment by karthikeyanamitysoft** [comment]
Dear Nandhinee,
Kindly move the deliverable to live server, and attach the complete deliverables with ER file.

**Comment by Nandhineedevi** [comment]
Completed moving File into Live Server.

[Live Import.zip](https://github.com/astpl1998/PPN-Power/files/6622652/Live.Import.zip)

**Comment by Senthilmurugan-B** [comment]
@karthikeyanamitysoft :
while the UDS in Live server system shown error like 
"Service Xml file not found ".
KIndly check and solve the issue ASAP
![image](https://user-images.githubusercontent.com/38855380/123396761-536c2c00-d5bf-11eb-9fb7-936bdc190724.png)

**Comment by mohanaamity** [comment]
@Senthilmurugan-B 

UDS issue resolved in PPn live server.Kindly check and confirm

Regards,
Mohana B

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket
