### ISSUE TITLE
I&P-Stock Ageing Report

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#23]
@AkashGleen 
Kindly start the PFS,
[Inv Ageing Report 31 March 2020  Summary.xlsx](https://github.com/astpl1998/PPN-Power/files/6088593/Inv.Ageing.Report.31.March.2020.Summary.xlsx)
[Inv Ageing Report 31 March 2020 base file.xlsx](https://github.com/astpl1998/PPN-Power/files/6088594/Inv.Ageing.Report.31.March.2020.base.file.xlsx)

**Comment by Senthilmurugan-B** [comment]
@Team: 
Report not available  in final customization list.

**Comment by raju-kurup** [comment]
Development is in hold, so closing this ticket
