### ISSUE TITLE
I&P-WH issue Report (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#24]
@AkashGleen 
kindly start the PFS,
[WH ISSUE REPORT.pdf](https://github.com/astpl1998/PPN-Power/files/6088602/WH.ISSUE.REPORT.pdf)

**Comment by Senthilmurugan-B** [comment]
@Team: 
Report not available  in final customization list.

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
