### ISSUE TITLE
I&P-Stock Report (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#25]
@eafaisal,
kindly start the PFS,
[Stock Report -Locatiowise - 03.03.2021.xlsx](https://github.com/astpl1998/PPN-Power/files/6088609/Stock.Report.-Locatiowise.-.03.03.2021.xlsx)

**Comment by Senthilmurugan-B** [comment]
@Team: 
Report not available  in final customization list.

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
