### ISSUE TITLE
I&P-stores ledger 

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#26]
@eafaisal,
kindly start the PFS,
[Stores Ledger with value.pdf](https://github.com/astpl1998/PPN-Power/files/6088620/Stores.Ledger.with.value.pdf)

**Comment by Senthilmurugan-B** [comment]
Report not in final customization list

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
