### ISSUE TITLE
I&P-TAG print in UPR

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#27]
@eafaisal 
Kindly start the PFS ,
we have a hard copy kindly attach the image

**Comment by eafaisal** [comment]
![Tag print in UPR](https://user-images.githubusercontent.com/65998153/116068871-596d8b80-a6a8-11eb-96ae-44b95563873d.jpeg)

**Comment by eafaisal** [comment]
PFS is completed
[Tag_Print_in_UPR.xlsx](https://github.com/astpl1998/PPN-Power/files/6381945/Tag_Print_in_UPR.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report and this is not in high priority

**Comment by BalaramanM** [comment]
Partnersandbox is not working , so that we can't able to do EDK design.Once it is working i will do needful

**Comment by BalaramanM** [comment]
Development completed . kindly check and revert back and move to next level
deliverables:
[TPIU.zip](https://github.com/astpl1998/PPN-Power/files/6606432/TPIU.zip)

Regards,
Balaraman M

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly start the testing 1

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 Has been completed

[Test cases_Tag Print_UPR.xlsx](https://github.com/astpl1998/PPN-Power/files/6614040/Test.cases_Tag.Print_UPR.xlsx)
[Test Result_Tag Print_UPR.pdf](https://github.com/astpl1998/PPN-Power/files/6614044/Test.Result_Tag.Print_UPR.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Client has given confirmation for this report.
Kindly check and move to live server.

PFS: [PFS.Tag_Print_in_UPR.xlsx](https://github.com/astpl1998/PPN-Power/files/6774621/PFS.Tag_Print_in_UPR.xlsx)
Latest Deliverables: [TPIU (1).zip](https://github.com/astpl1998/PPN-Power/files/6774625/TPIU.1.zip)
Testing1 Test Case: [Testing1_Test_Case_Tag_Print_in_UPR.xlsx](https://github.com/astpl1998/PPN-Power/files/6774631/Testing1_Test_Case_Tag_Print_in_UPR.xlsx)
Testing1 Test Result: [Testing1_Test_Result_Tag_Print_in_UPR.pdf](https://github.com/astpl1998/PPN-Power/files/6774635/Testing1_Test_Result_Tag_Print_in_UPR.pdf)
Testing2 Test Case: [Testing2_Test_Case_Tag_Print_in_UPR.xlsx](https://github.com/astpl1998/PPN-Power/files/6774637/Testing2_Test_Case_Tag_Print_in_UPR.xlsx)
Testing2 Test Result: [Testing2_Test_Result_Tag_Print_in_UPR.pdf](https://github.com/astpl1998/PPN-Power/files/6774640/Testing2_Test_Result_Tag_Print_in_UPR.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Move this report from Test to Live Server

**Comment by BalaramanM** [comment]
Development completed .While clicking print button in live server error thown like "Service XML file error".Rised Rtrack for regarding that issue .Once solution is provided i will do needful

Regards,
Balaraman

**Comment by BalaramanM** [comment]
@eafaisal bro
Development completed in live server .Kindly check and revert back


Regards,
Balaraman M

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Deployment done in live server, so closing this ticket

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket
