### ISSUE TITLE
EAM-Additional Permit Transaction

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#29]
@AkashGleen 
Kindly start the PFS,
Before start, we need to Freeze the screen design

**Comment by eafaisal** [comment]
@raju-kurup Sir,

PFS is completed.

[Maintain_Additional_Clearance_Permit.xlsx](https://github.com/astpl1998/PPN-Power/files/6134344/Maintain_Additional_Clearance_Permit.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
The PFS is updated.

[Maintain_Additional_Clearance_Permit_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6700936/Maintain_Additional_Clearance_Permit_V1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
As the column 15 (No of persons working in confined space : _______________) is added in the UDS of Additional Hard Copy Permit (Issue #10 ) it's removed from PFS.

Updated PFS: 
[Maintain_Additional_Clearance_Permit_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6702259/Maintain_Additional_Clearance_Permit_V1.2.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup 

As per the mail reference dated on 24/06/2021,customer agreed the changes.
Kindly assign to Karthi for development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development as per the PFS attached.

**Comment by karthikeyanamitysoft** [comment]
Please clarify , what is this customer format image, when it will launch,

![image](https://user-images.githubusercontent.com/40713407/123413054-ee6d0200-d5cf-11eb-9631-2ee941555797.png)

**Comment by raju-kurup** [comment]
@eafaisal : provide the detail asked by Karthi for further development

**Comment by eafaisal** [comment]
@karthikeyanamitysoft 

This is the screen.Customer format image is removed from PFS.
For this screen design customer agreed.
Updated PFS: [Maintain_Additional_Clearance_Permit_V1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/6723380/Maintain_Additional_Clearance_Permit_V1.3.xlsx)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal bro
As we disccused ,i need a clarification for column 1& 14 which is mentioned in PFS

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

The following changes have been done in PFS.
1. The sample transaction format is mentioned in column 1
2. The column name and field type are changed in column 14
3. The column 15 (Name) is added 
4. For the **Additional Clearance Permit No** field (column 1) the help screen is attached in Sheet 1

Updated PFS: [PFS.Maintain_Additional_Clearance_Permit_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6732997/PFS.Maintain_Additional_Clearance_Permit_V1.1.xlsx)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
As we discussed,Development completed.Rtrack rised for column 20 for wrong value fetching.Please do testing fof except that column

Regards,
Balaraman

**Comment by eafaisal** [comment]
@viki18790 

Kindy do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@BalaramanM 

Only the transaction with '**Fresh**' status should be approved.
The column for **Approve** button is updated.
[PFS.Maintain_Additional_Clearance_Permit_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6805823/PFS.Maintain_Additional_Clearance_Permit_V1.2.xlsx)
Kindly update.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal bro
Development completed and that column also updated .Kindly check and revert back

Regards,
Balaraman

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1.

Regards,
Faisal

**Comment by viki18790** [comment]
@BalaramanM 

In Clearance Permit Numbering Type already we did one customization as a Double Numbering Series, while choosing the Clearance Numbering Type system showing authorized Clearance Permit number( CL/000114/21-22/01), while I'm on entering on this Clearance Permit Number, the details are not fetching. 
![Additional CLP](https://user-images.githubusercontent.com/73546890/126132033-d7cb3335-f7da-4aa2-bd33-c05aba23272a.png)

**Comment by BalaramanM** [comment]
@viki18790 bro,
There is no record against above mentioned CL number ( CL/000114/21-22/01) .Pls find the below attached screenshot FYI
![Screenshot (209)](https://user-images.githubusercontent.com/80749490/126141960-c90b9ea9-81a3-4d06-87d6-1b8cdda67621.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

As we discussed, it's unable to approve the transaction ACL/000005/21-22.
Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal bro
Error resolved.Kindly check

Regards,
Balaraman

**Comment by Senthilmurugan-B** [comment]
@eafaisal 👍 
Testing 2 completed kindly send mail to the customer.
the description should fetch from work order when entering in the work order No.

**Comment by eafaisal** [comment]
@BalaramanM 

The transaction numbers are duplicated.
The transaction **ACL/000010/21-22** is created 5 times.
Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Error resolved now.pls find below attached screen shot
![image](https://user-images.githubusercontent.com/80749490/129539879-669df8a2-b42b-4f4f-93e3-01e4aed1dc77.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
Testing 2 is completed.

![image](https://user-images.githubusercontent.com/65998153/130427579-d41dc5be-41b5-4f5d-aeac-0046f9af41ae.png)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: 
[Testing2_Test_Case_Additional_Permit_Transaction.xlsx](https://github.com/astpl1998/PPN-Power/files/7070537/Testing2_Test_Case_Additional_Permit_Transaction.xlsx)
Test Result: 
![Testing2_Test_Result_Additional_Permit_Transaction](https://user-images.githubusercontent.com/65998153/131214323-43041aee-3819-45ac-8601-a0c06667749f.png)

**Comment by BalaramanM** [comment]
@eafaisal bro,
Pls find the attached latest deliverables.
[MACP.zip](https://github.com/astpl1998/PPN-Power/files/7070546/MACP.zip)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

If we select the _Clearance Permit_ in lens and do the on enter, the details from the Clearance Permit are not fetched in screen.
Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal bro,
There is no record exists for given employee code .pls find below attached screenshot .
![image](https://user-images.githubusercontent.com/80749490/139525983-5722abda-057d-4dc5-8c4f-356bd68adcb0.png)


Regards,
Balaraman

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer agreed this report.
![image](https://user-images.githubusercontent.com/65998153/142565921-f248e724-f99a-4c09-a5c2-58c2ce78339c.png)

Kindly move this to deploy in live server.
PFS: [PFS.Maintain_Additional_Clearance_Permit_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7567780/PFS.Maintain_Additional_Clearance_Permit_V1.2.xlsx)
 Latest Deliverables: [MACP.zip](https://github.com/astpl1998/PPN-Power/files/7567783/MACP.zip)
 Test Case 1:[Testing1_Test_Case_Additional_Permit_Transaction.xlsx](https://github.com/astpl1998/PPN-Power/files/7567785/Testing1_Test_Case_Additional_Permit_Transaction.xlsx)
 Test Result 1: ![Testing1_Test_Result_Additional_Permit_Transaction](https://user-images.githubusercontent.com/65998153/142566042-b20e788b-2f95-4a0b-b40e-82d85e74d3f8.png)
Test Case 2: [Testing2_Test_Case_Additional_Permit_Transaction.xlsx](https://github.com/astpl1998/PPN-Power/files/7567789/Testing2_Test_Case_Additional_Permit_Transaction.xlsx)
 Test Result 2: ![Testing2_Test_Result_Additional_Permit_Transaction](https://user-images.githubusercontent.com/65998153/142566114-491c1f57-277c-483a-8d13-326bacfc593d.png)
 
Regards,
Faisal

**Comment by raju-kurup** [comment]
Testing completed by us and PPN accepted, so please move this development to Live server

**Comment by BalaramanM** [comment]
@eafaisal bro
Development completed in live server.Kindly check and confirm
![image](https://user-images.githubusercontent.com/80749490/142717945-4b263451-af94-4e96-883a-6d8a1c058b91.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Being development completed and deployed in live, we are closing this ticket.
