### ISSUE TITLE
P&S-Purchase Order Print

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#3]
@Team,
Customer format,
![PO Print_2](https://user-images.githubusercontent.com/38855380/108484759-2c74b500-72c2-11eb-883f-16136437e3fe.jpeg)
![PO Print_1](https://user-images.githubusercontent.com/38855380/108484762-2da5e200-72c2-11eb-8493-53f90e1a2681.jpeg)

**Comment by Senthilmurugan-B** [comment]
@eafaisal 
Kindly start the PFS

**Comment by eafaisal** [comment]
Sir,

The PFS is completed.
Kindly move to development.

[Purchase_Order_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6054156/Purchase_Order_Print.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
Sir,

Updated PFS is attached.

[Purchase_Order_Print_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6100650/Purchase_Order_Print_V1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup  Sir,

Updated copy of PFS
[Purchase_Order_Print_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6141087/Purchase_Order_Print_V1.1.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development.

**Comment by Narendiranath** [comment]
Hi Faisal,

            Development Completed. Kindly check. PFA Latest deliverables and Test result for your ref.

[Deliverables.zip](https://github.com/astpl1998/PPN-Power/files/6289806/Deliverables.zip)

[PO_Print_Final.pdf](https://github.com/astpl1998/PPN-Power/files/6289808/PO_Print_Final.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
customer format with tax

![1620811902831](https://user-images.githubusercontent.com/65998153/117953437-a6519300-b333-11eb-9d07-ddefded7cb69.JPEG)

**Comment by eafaisal** [comment]
The TCD details added for 3 scenarios in PFS.
1. Line level TCD
2. Document level TCD
3. Line level and document level TCD

[Purchase_Order_Print_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6466178/Purchase_Order_Print_V1.2.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

              As we discussed pls update the PFS & allocate to me.

Regards,
Naren

**Comment by eafaisal** [comment]
@Narendiranath 

The changed fileds and related columns are highlited by yellow.
In line level tax,in case of CGST and SGST,it should come seperately in two lines
(Ex: CG09,SG09)

Updated PFS: [Purchase_Order_Print_V1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/6482418/Purchase_Order_Print_V1.3.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

            Development completed. Kindly check. PFA Latest deliverable & Test result for your ref.

[Latest Deliverable.zip](https://github.com/astpl1998/PPN-Power/files/6516330/Latest.Deliverable.zip)

[PO_000082_20_21.pdf](https://github.com/astpl1998/PPN-Power/files/6516333/PO_000082_20_21.pdf)
[PO_000083_20_21.pdf](https://github.com/astpl1998/PPN-Power/files/6516336/PO_000083_20_21.pdf)
[PO_000081_20_21.pdf](https://github.com/astpl1998/PPN-Power/files/6516337/PO_000081_20_21.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly start the testing 1

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,
 
As we discussed i changed the county code value to currency code. PFA Latest deliverable for your ref. Kindly check.

[Deliverable.zip](https://github.com/astpl1998/PPN-Power/files/6526189/Deliverable.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
The data source for 'Currency Code' field is updated in PFS.

[Purchase_Order_Print_V1.4.xlsx](https://github.com/astpl1998/PPN-Power/files/6529873/Purchase_Order_Print_V1.4.xlsx)

**Comment by eafaisal** [comment]
@Narendiranath 

For PO PO/000034/21-22 the 'Total' column values for line items 2,3 are wrong.
Kindly check.

[PO_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6532067/PO_Print.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

           PFA Latest Deliverable for your ref.

[Deliverables.zip](https://github.com/astpl1998/PPN-Power/files/6532288/Deliverables.zip)

**Comment by eafaisal** [comment]
@Narendiranath 

The Total values for line items are wrong for PO in print.
The total value should be as follows.(The printed values are in bracket)
1. 6724.94 (6372.00)
2. 7845.76 (7434.00)
3. 4483.30 (4248.00)

Also the tax amount for line item 3 is not fetched in print.
The tax value is CG09-Rs 324.00 and SG 09- Rs 324.

[PO_000045.pdf](https://github.com/astpl1998/PPN-Power/files/6538320/PO_000045.pdf)

Kindly check.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

              Development completed. Kindly check & Revert back. PFA Latest deliverable & Test result for your ref.

[Deliverable.zip](https://github.com/astpl1998/PPN-Power/files/6540794/Deliverable.zip)

[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6540797/Test_Result.pdf)

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by viki18790** [comment]
@Narendiranath 

The PO Print mentioned in the PFS is in Landscape mode and the screenshots attached in Github is in Landscape Format. Kindly change the orientation of the PO Print from Portrait to Landscape.
[Purchase_Order_Print_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6551418/Purchase_Order_Print_V1.1.xlsx)

Regards, 
Viignesh

**Comment by Narendiranath** [comment]
Hi Viignesh,

               PO Print changed from Portrait to Landscape. Kindly check.

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The column level requirements for following address are changed
1. Address in header
2. Shipped to address
3. Delivered to address

The sheduled quantity and scheduled date values are updated with Schedule Type='Staggered' in Actual Test Result sheet.
Updated PFS: [Purchase_Order_Print_V1.5.xlsx](https://github.com/astpl1998/PPN-Power/files/6615499/Purchase_Order_Print_V1.5.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the modification as per the latest PFS

**Comment by eafaisal** [comment]
@Narendiranath 

As we discussed,the address ids are created for accounting units PPN_TK_PFB,PPN_PL_PFB,PPN_CORP_PFB,PPN_CH_PFB with the same names.It's updated in PFS.

[Purchase_Order_Print_V1.6.xlsx](https://github.com/astpl1998/PPN-Power/files/6641914/Purchase_Order_Print_V1.6.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

Development rework has been completed. Kindly check and revert back. PFA Latest Deliverable & Test result for your ref.

[Deliverable V.4.zip](https://github.com/astpl1998/PPN-Power/files/6641940/Deliverable.V.4.zip)

[Test_Result_V1.pdf](https://github.com/astpl1998/PPN-Power/files/6641941/Test_Result_V1.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@Narendiranath 

The  following points should be added in print.

1. There are two copies 'Original copy to supplier' and 'office copy'
2. The page number in all pages
3. The Terms and Condtions

Kindly update.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

           Above mentioned points are corrected. Kindly check and revert back. PFA Latest Deliverable & Test Result for your ref.

[Deliverable V.5.zip](https://github.com/astpl1998/PPN-Power/files/6653718/Deliverable.V.5.zip)

[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6653731/Test_Result.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@Narendiranath 

In PO print(Inter state PO) in 'Tax Type' and 'Amount' columns the '0' is coming in next line.
It should be removed.
It's highlighted in attachment.

[PO-PRINT_INTERSTATE.pdf](https://github.com/astpl1998/PPN-Power/files/6661752/PO-PRINT_INTERSTATE.pdf)

Kindly check.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

               Above mentioned points are done. Kindly check and revert back. PFA Latest Deliverable & Test result for your ref.

[Deliverable V.6.zip](https://github.com/astpl1998/PPN-Power/files/6664836/Deliverable.V.6.zip)

[Test_Result_V6.pdf](https://github.com/astpl1998/PPN-Power/files/6664839/Test_Result_V6.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again

Regards,
Faisal

**Comment by eafaisal** [comment]
@Narendiranath 

In the print out the following issues are found out.
1. The item T200000081 is removed in amendment.But in print it's coming.
2. All items are dublicated in print
3. Except item 200000401 all items' Sch.Qty and Sch.date are dublicated in print.

The print is attached.Kindly check.
[PO PRINT_Amendment.pdf](https://github.com/astpl1998/PPN-Power/files/6668312/PO.PRINT_Amendment.pdf)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

         Above mentioned points are done. Kindly check and revert back. PFA Latest Deliverable & Test result for your ref.

[Deliverable V.7.zip](https://github.com/astpl1998/PPN-Power/files/6669078/Deliverable.V.7.zip)

[Test_Result_V7.pdf](https://github.com/astpl1998/PPN-Power/files/6669080/Test_Result_V7.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by viki18790** [comment]
@eafaisal 

The various scenarios of Testing-1 are completed. Please find attached the test cases and various test results 

[Testing1_Test_Case_PO_Print_All scenarios.xlsx](https://github.com/astpl1998/PPN-Power/files/6686422/Testing1_Test_Case_PO_Print_All.scenarios.xlsx)
[test result for interstate.pdf](https://github.com/astpl1998/PPN-Power/files/6686424/test.result.for.interstate.pdf)
[test result for Adhoc PO.pdf](https://github.com/astpl1998/PPN-Power/files/6686425/test.result.for.Adhoc.PO.pdf)
[Test Result for Import PO.pdf](https://github.com/astpl1998/PPN-Power/files/6686426/Test.Result.for.Import.PO.pdf)
[Test Result for Local PO.pdf](https://github.com/astpl1998/PPN-Power/files/6686427/Test.Result.for.Local.PO.pdf)

**Comment by eafaisal** [comment]
Testing 2 is completed

Test Case: [Testing2_Test_Case_PO_Print_All.scenarios.xlsx](https://github.com/astpl1998/PPN-Power/files/6707775/Testing2_Test_Case_PO_Print_All.scenarios.xlsx)

Test Results:
[Testing2_Test_Result_Adhoc_PO.pdf](https://github.com/astpl1998/PPN-Power/files/6707781/Testing2_Test_Result_Adhoc_PO.pdf)
[Testing2_Test_Result_Import_PO.pdf](https://github.com/astpl1998/PPN-Power/files/6707783/Testing2_Test_Result_Import_PO.pdf)
[Testing2_Test_Result_InterState_PO.pdf](https://github.com/astpl1998/PPN-Power/files/6707784/Testing2_Test_Result_InterState_PO.pdf)
[Testing2_Test_Result_Local_PO.pdf](https://github.com/astpl1998/PPN-Power/files/6707785/Testing2_Test_Result_Local_PO.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The customer has requested the following changes.
1. The PO print out is going ouside the A4 size.It should be fixed
2. The logo is not clear
3. In header it should be  'original copy'
4. In supplier details instead of state code the 'state' should be fetched
5. In billed to and shipped to addresses,the company name should be in bigger font.
6. In tax type there should be CGST,SGST instead of tax variant codes
7. The contents in Sch.Qty and Sch.Date columns should alligned properly

The changes are updated in PFS.
[Purchase_Order_Print_V1.7.xlsx](https://github.com/astpl1998/PPN-Power/files/6746789/Purchase_Order_Print_V1.7.xlsx)

Customer print: 
[MAGNA PO PRINT -DRAFT.pdf](https://github.com/astpl1998/PPN-Power/files/6746801/MAGNA.PO.PRINT.-DRAFT.pdf)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed please do the modification in PO Screen

**Comment by Narendiranath** [comment]
Hi Faisal,

               Development Completed. Kindly check & Revert Back. PFA Test Result & Latest Deliverable For your ref.
[Test_Result_V9.pdf](https://github.com/astpl1998/PPN-Power/files/6754527/Test_Result_V9.pdf)
[Deliverable V.9.zip](https://github.com/astpl1998/PPN-Power/files/6754499/Deliverable.V.9.zip)
Regards,
Naren

**Comment by eafaisal** [comment]
Test result: [Testing2_Test_Result_PO_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6776881/Testing2_Test_Result_PO_Print.pdf)

**Comment by eafaisal** [comment]
@Narendiranath 

Client asked to add amendment no in PO print.
The column **N8 (Amendment No)** is added in PFS.
[Purchase_Order_Print_V1.8.xlsx](https://github.com/astpl1998/PPN-Power/files/6815226/Purchase_Order_Print_V1.8.xlsx)

Kindly update.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The client requested the following alignment changes.

1. The font size of company name, address in header to be reduced
2. In 'Details of Supplier' the space below the address to be removed
3. In billed to and shipped to addresses,the space below the address to be removed
4. The width of columns HSN and Sch.Date to be increased
5. The font size of PO value (In Words) to be increased. (same like multi line content font)
6. The title in second copy also to be changed to '**original copy**' instead of 'office copy'
7. The font size of points in PO Terms and Coditions (second page) to be increased (same like multi line content font).

The PFS is updated.
[Purchase_Order_Print_V1.9.xlsx](https://github.com/astpl1998/PPN-Power/files/6815912/Purchase_Order_Print_V1.9.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the alignment in the PO mentioned in PFS and Comments.

**Comment by Narendiranath** [comment]
Hi Faisal,

            Above mentioned changes are done. Kindly check. PFA Latest test result for your ref.

[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6846292/Test_Result.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Client has given confirmation for this report. (Mail date 20/07/2021)
Kindly move to development to deploy.

PFS: [PFS.Purchase_Order_Print_V1.9.xlsx](https://github.com/astpl1998/PPN-Power/files/6847248/PFS.Purchase_Order_Print_V1.9.xlsx)
Latest Deliverables: [Deliverable.V.12.zip](https://github.com/astpl1998/PPN-Power/files/6847252/Deliverable.V.12.zip)
Test Case 1: [Testing1_Test_Case_PO_Print_All.scenarios.xlsx](https://github.com/astpl1998/PPN-Power/files/6847256/Testing1_Test_Case_PO_Print_All.scenarios.xlsx)
Test Result 1: [Testing1_Test_Result_PO_Print.zip](https://github.com/astpl1998/PPN-Power/files/6847263/Testing1_Test_Result_PO_Print.zip)
Test Case 2: [Testing2_Test_Case_PO_Print_All.scenarios.xlsx](https://github.com/astpl1998/PPN-Power/files/6847272/Testing2_Test_Case_PO_Print_All.scenarios.xlsx)
Test Result 2: [Testing2_Test_Result_PO_Print.zip](https://github.com/astpl1998/PPN-Power/files/6847275/Testing2_Test_Result_PO_Print.zip)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please move this development to Live Server

**Comment by Narendiranath** [comment]
Hi Faisal,

          Deployment in Live Server is completed. Kindly check & Revert back. PFA Latest Deliverables for your ref.

[PPNE-34 -new.zip](https://github.com/astpl1998/PPN-Power/files/6872202/PPNE-34.-new.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The logic for column **Total Value** in line level is changed.
The PFS is updated.
[PFS.Purchase_Order_Print_V1.10.xlsx](https://github.com/astpl1998/PPN-Power/files/6985907/PFS.Purchase_Order_Print_V1.10.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

         Above changes is completed. Kindly check. PFA Latest Deliverables for your ref.

[Deliverable V.13.zip](https://github.com/astpl1998/PPN-Power/files/6985960/Deliverable.V.13.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
Testing is completed
Test Case: [Testing2_Test_Case_PO_Print_All.scenarios.xlsx](https://github.com/astpl1998/PPN-Power/files/6986143/Testing2_Test_Case_PO_Print_All.scenarios.xlsx)
Test Result: [Testing2_Test_Result_PO_Print.zip](https://github.com/astpl1998/PPN-Power/files/6986149/Testing2_Test_Result_PO_Print.zip)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup SIr,

As per client's requirement,for amended PO the **PO Date** should be **Amendment Date**.
The PFS is updated.
[PFS.Purchase_Order_Print_V1.11.xlsx](https://github.com/astpl1998/PPN-Power/files/7029225/PFS.Purchase_Order_Print_V1.11.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in PO

If PO Amendment No is 0 then take PO date and if PO Amendment No is greater than 0 then take Amendment date as discussed

**Comment by Narendiranath** [comment]
Hi Faisal,

           Above mentioed logic is applied for both Live & UAT. PFA Latest Deliverable for your ref.

[Deliverable V.14.zip](https://github.com/astpl1998/PPN-Power/files/7037773/Deliverable.V.14.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
The amendment date is fetched in PO Date correctly.
[PO print.pdf](https://github.com/astpl1998/PPN-Power/files/7043635/PO.print.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket

**Comment by eafaisal** [comment]
@raju-kurup Sir,

If line items are more than 12, the values in **Sch.Qty** and **Sch Date** colums are not printed.
Kindly move to development to resolve this issue.
The sample print out is attached.
[PO - 136 PRINT.pdf](https://github.com/astpl1998/PPN-Power/files/7574038/PO.-.136.PRINT.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please look into this issue and give solutions.

**Comment by eafaisal** [comment]
@Narendiranath 

As discussed with customer,maximum 150 line items may be in PO print.

**Comment by Narendiranath** [comment]
Hi Faisal,

If line items are more than 12, the values in Sch.Qty and Sch Date columns are now printed. In PO Print Item codes are came duplicate. So that only the serial numbers are came not properly. Once item codes are come without duplicate the  serial numbers are come properly. Kindly check & Revert back. PFA Latest deliverable & Test result for your ref.

[Deliverables.zip](https://github.com/astpl1998/PPN-Power/files/7631293/Deliverables.zip)
[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/7631294/Test_Result.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
Testing is completed.
[PO Print for PPO000136.pdf](https://github.com/astpl1998/PPN-Power/files/7639090/PO.Print.for.PPO000136.pdf)
Now the **Sch.Qty** and **Sch Date** for all items are printed.
But there are duplicate item codes becaused of PR to PO conversion.
So the serial numbers are not in sequence.
For this issue the rTrack **PPNE-163** was raised to Ramco.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The report was deployed in live server.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Being correction done and deployed in live, we are closing this issue
