### ISSUE TITLE
EAM-Excess Material WO MRQ print out

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#30]
@AkashGleen 
Kindly start the PFS,
refer to the Wo MRQ print out the format and attach the Image

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Excess Material WO MRQ print out PFS as been Completed.

[Excess Material WO MRQ print out PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6140785/Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Excess Material WO MRQ print out PFS as been Completed.

[Excess Material WO MRQ print out PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6148211/Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

Excess Material WO MRQ Print PFS as Discuss Correction as been Changed Kindly Move On Next Level

[Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6363293/Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop the UDS and Print out as per the PFS attached

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal Development completed .kindly check and revert
[AMITYUSER__74301031_3214779b-9d10-44ef-a2d7-5e389f70fefa.pdf](https://github.com/astpl1998/PPN-Power/files/6749456/AMITYUSER__74301031_3214779b-9d10-44ef-a2d7-5e389f70fefa.pdf)
regards,
preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1

Regards,
Faisal

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

In testing the following issues were found.
1. The reserved items from work order are not fetched to UDS screen
2. While doing the on enter after choosing the item code in UDS, 'Service Xml file not found' error is thrown.

Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
there is no item code available on the screen

Regards,
preetha

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

There spare parts should be fetched from the path "Enterprise Asset Management--->Work Order Execution--->View Work Order Actuals--->View Part Actuals"
The spare parts are 3710300501, 5431611036.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
1.Above issues are cleared kindly check and revert.
2. on enter after choosing the item code in UDS, 'Service Xml file not found' error is thrown  only pending .

Regrads,
Preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

After saving the items, while printing, it's throwing the 'pop ups are blocked' error.
If we click the SAVE button more than one time,it's generating multiple records in UDS screen.
Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Above issues are cleared ,kindly check

Regrads,
preetha

**Comment by Senthilmurugan-B** [comment]
@viki18790 :
Above mentioned issues are resolved by preetha.
kindly start the testing.

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

In UDS screen, the values in Qty and Description columns are interchanged.
Kindly check.
![image](https://user-images.githubusercontent.com/65998153/125238819-6b54e700-e305-11eb-8731-e730381e6e3e.png)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Above mentioned issues are cleared,kindly check it.
Regards,
Preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

The spare parts details from work order actuals are not fetched in UDS screen while doing on enter.
The WO No is WO/0059/21-22.
Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Above mentioned issues are cleared.
there is no logic given for quantity.
kindly check
![Screenshot (90)](https://user-images.githubusercontent.com/85933899/125949060-ad281917-9d19-4991-b797-cc77f36454a6.png)
Regards,
Preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by viki18790** [comment]
@PreethaGopalakrishnan 

Ref Work Order: WO/0059/21-22
The report has the following fields missing 
1. WO Date
2. WO Descriptions
3. Dept Name
4. Cost Center
[womrq testing1.pdf](https://github.com/astpl1998/PPN-Power/files/6838222/womrq.testing1.pdf)

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
Above mention corrections are cleared.
kindly check.

Regards,
Preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing.

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

In print out the following issues were found.
1. WO Description is not printed fully
2. Item description is not printed fully
3. For item 4070126001 the Qty Already Issued is wrong (It should be 12.00)
4. There is no 'Qty Already Issued' for item 100000021. But it's printed as 10.00 by mistake.
5. The Qty values should have two decimals only (10.00). Now it's eight decimals (Ex.10.00000000)

The errors are marked in print out.
[Exess WO MRQ print.pdf](https://github.com/astpl1998/PPN-Power/files/6867012/Exess.WO.MRQ.print.pdf)

Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mention issues are cleared.
kindly check
Regards,
preetha
[excess_material_wo_print.pdf](https://github.com/astpl1998/PPN-Power/files/6868989/excess_material_wo_print.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

The item codes 100000021 and 4070131009 which are not given in UDS also printed in report.
Kindly check.
[excess.pdf](https://github.com/astpl1998/PPN-Power/files/6872181/excess.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are cleared.
kindly check.
Regards,
preetha
[excess_27_7_21.pdf](https://github.com/astpl1998/PPN-Power/files/6884689/excess_27_7_21.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

The item code 4070131009,which was not selected in UDS is also printed with no quantity.
Kindly check.

[Excess.WO.MRQ.pdf](https://github.com/astpl1998/PPN-Power/files/6910783/Excess.WO.MRQ.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are cleared.
1.please first save the value and then give print.
kindly check.
Regards,
preetha
[wo_no_3_8_21.pdf](https://github.com/astpl1998/PPN-Power/files/6922311/wo_no_3_8_21.pdf)

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

There are two issues.
1. After saving items with quantities, the screen is vanished
2. While printing, the **there is no record exists for given work order number please save first** error is thrown.
I have checked with WO/0059/21-22 and WO/0065/21-22.

Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The mentioned issues are solved.
1.please save the value  and then give print.
kindly check.
[workorder1.pdf](https://github.com/astpl1998/PPN-Power/files/6930609/workorder1.pdf)
[workorder2.pdf](https://github.com/astpl1998/PPN-Power/files/6930612/workorder2.pdf)
Regards,
preetha

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

I added a new item and gave quantity. But after saving, the new item got vanished.
Only exsiting items come in print.
Kindly check.

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are cleared.
kindly check.
[wo2_9821.pdf](https://github.com/astpl1998/PPN-Power/files/6954255/wo2_9821.pdf)
Regards,
preetha

**Comment by eafaisal** [comment]
@viki18790 

Kindly start the testing 2.

Regards,
Faisal

**Comment by viki18790** [comment]
@eafaisal 

Testing 2 Completed.
Test Case: 
[Ex_Mat_WO-MRQ Print-Testing 2.xlsx](https://github.com/astpl1998/PPN-Power/files/6992429/Ex_Mat_WO-MRQ.Print-Testing.2.xlsx)

Test Result: 
[excess-mat_WO MRQ Print-testing2.pdf](https://github.com/astpl1998/PPN-Power/files/6992435/excess-mat_WO.MRQ.Print-testing2.pdf)


Regards, 

Viignesh S

**Comment by eafaisal** [comment]
@PreethaGopalakrishnan 

The following issues are found in print out.
1. WO Description is not printed fully
2. Some spelling mistakes are marked
[excess-mat_WO.MRQ.Print-testing2.pdf](https://github.com/astpl1998/PPN-Power/files/6997566/excess-mat_WO.MRQ.Print-testing2.pdf)

The spelling mistakes are corrected in PFS.
[Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6997569/Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
The above mentioned issues are cleared.
kindly check.
Regards,
preetha
[wo17821.pdf](https://github.com/astpl1998/PPN-Power/files/6998594/wo17821.pdf)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Ex_Mat_WO-MRQ.Print-Testing.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6999440/Ex_Mat_WO-MRQ.Print-Testing.2.xlsx)
Test Result: [excess-mat_WO.MRQ.Print-testing2.pdf](https://github.com/astpl1998/PPN-Power/files/6999441/excess-mat_WO.MRQ.Print-testing2.pdf)

Regards,
Faisal

**Comment by PreethaGopalakrishnan** [comment]
@eafaisal 
[latest deliverables.zip](https://github.com/astpl1998/PPN-Power/files/7038931/latest.deliverables.zip)
Regards ,
preetha

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer agreed the report to deploy in live server (Mail date 23.08.2021)
Kindly move to development.

PFS: [Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/7038992/Excess.Material.WO.MRQ.print.out.PFS.v1.0.xlsx)
Latest Deliverables: [latest.deliverables.zip](https://github.com/astpl1998/PPN-Power/files/7038996/latest.deliverables.zip)
Test Case 1: [Testing1_Test_Case_Ex_Mat_WO_MRQ_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/7038997/Testing1_Test_Case_Ex_Mat_WO_MRQ_Print.xlsx)
Test Result 1: [Testing1_Test_Result_Ex_Mat_WO_MRQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7039000/Testing1_Test_Result_Ex_Mat_WO_MRQ_Print.pdf)
Test Case 2: [Testing2_Test_Case_Ex_Mat_WO_MRQ_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/7039002/Testing2_Test_Case_Ex_Mat_WO_MRQ_Print.xlsx)
Test Result 2: [Testing2_Test_Result_Ex_Mat_WO_MRQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7039003/Testing2_Test_Result_Ex_Mat_WO_MRQ_Print.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
