### ISSUE TITLE
EAM-EOH Entry Screen (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#31]
@eafaisal 
Kindly start the PFS,
we have a hard copy and attach the image

**Comment by eafaisal** [comment]
![EOH_Entry_Screen](https://user-images.githubusercontent.com/65998153/111417935-c6d2e780-870c-11eb-8034-3b6bd271f485.JPEG)

**Comment by Senthilmurugan-B** [comment]
@team:
asper the PPN mail received from 31/05/2021 with the attachment of the Consolidated Open points list in that they declared as deferred for this report

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
