### ISSUE TITLE
S&S-Scrap sale order print out

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#32]
@AkashGleen 
Kindly start the PFS,
[Scrap sale order format.xlsx](https://github.com/astpl1998/PPN-Power/files/6088699/Scrap.sale.order.format.xlsx)

**Comment by Senthilmurugan-B** [comment]
Report not in final list

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
