### ISSUE TITLE
P&S-Inspection Intimation Slip

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#4]
@Team,
Customer Format,
![Inspection_Intimation_Slip_1](https://user-images.githubusercontent.com/38855380/108486820-85454d00-72c4-11eb-8b59-3f99349bbca2.jpeg)
![Inspection_Intimation_Slip_2](https://user-images.githubusercontent.com/38855380/108486823-86767a00-72c4-11eb-8aa9-c990384041a4.jpeg)

**Comment by Senthilmurugan-B** [comment]
@AkashGleen
Kindly update the PFS

**Comment by AkashGleen** [comment]
@raju-kurup Sir, 

Inspection Intimation Slip PFS as been Completed Move on Next Level.

[Inspection Intimation Slip PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6529626/Inspection.Intimation.Slip.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report and this is in high priority list

**Comment by Narendiranath** [comment]
Hi Akash,

            Development Completed. Kindly check and revert back. PFA Latest Deliverables & Test Result for your ref.

[Material_discre.zip](https://github.com/astpl1998/PPN-Power/files/6631306/Material_discre.zip)

[Test_Result_V1.pdf](https://github.com/astpl1998/PPN-Power/files/6631310/Test_Result_V1.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly start the testing 1

**Comment by eafaisal** [comment]
@Narendiranath 

The print is blank and no values are fetched.
Kindly check

The MIN transaction number is MIN/000014/21-22.

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

           Development Completed. Kindly check & Revert back. PFA Latest deliverables & Test Result for your ref.

[Deliverable V.3.zip](https://github.com/astpl1998/PPN-Power/files/6655444/Deliverable.V.3.zip)

[Test_Result_V3.pdf](https://github.com/astpl1998/PPN-Power/files/6655451/Test_Result_V3.pdf)

Regardss,
Naren

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again

Regards,
Faisal

**Comment by eafaisal** [comment]
@Narendiranath 

1. The PR number PR/000014/21-22 is missing in print.
2. The details of item code 5631319013 is dublicated in print
3. The serial numbers in 'PO Line No' column are in wrong series.

They are marked in yellow in print.
[Test Result 1_IIS.pdf](https://github.com/astpl1998/PPN-Power/files/6660504/Test.Result.1_IIS.pdf)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

        Above mentioned points are done. Kindly check & Revert back. PFA Latest deliverable & Test result for your ref.

[Deliverable V.4.zip](https://github.com/astpl1998/PPN-Power/files/6664688/Deliverable.V.4.zip)

[Test_Result_V4.pdf](https://github.com/astpl1998/PPN-Power/files/6664689/Test_Result_V4.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again.

Regards,
Faisal

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 has been completed

[Test Cases_Inspection Intimation.xlsx](https://github.com/astpl1998/PPN-Power/files/6668641/Test.Cases_Inspection.Intimation.xlsx)
[Test Result_Inspection Intimation.pdf](https://github.com/astpl1998/PPN-Power/files/6668642/Test.Result_Inspection.Intimation.pdf)

**Comment by eafaisal** [comment]
@Narendiranath 

In the print,the following issues are found.

1. The indenter numbers are missing against PR numbers
2. All items are triplicated

It's highlighted in print out.Kindly check.
[Inspection_Intimation_Slip.pdf](https://github.com/astpl1998/PPN-Power/files/6669221/Inspection_Intimation_Slip.pdf)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

          Above mentioned points are done. Kindly check & Revert back. PFA Latest deliverable & Test result for your ref.

[Deliverable V.5.zip](https://github.com/astpl1998/PPN-Power/files/6669463/Deliverable.V.5.zip)

[Test_Result_V5.pdf](https://github.com/astpl1998/PPN-Power/files/6669465/Test_Result_V5.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_Inspection.Intimation_Slip.xlsx](https://github.com/astpl1998/PPN-Power/files/6670245/Testing2_Test_Case_Inspection.Intimation_Slip.xlsx)
Test Result:[Testing2_Test_Result_Inspection.Intimation_Slip.pdf](https://github.com/astpl1998/PPN-Power/files/6670254/Testing2_Test_Result_Inspection.Intimation_Slip.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per client's request, the following points are updated in PFS
1. The inspection intimation slip and inspection report (annexture) should be in seperate print outs.
2. The  inspection intimation slip should be in portrait mode and inspection report (annexture) should be in landscape mode.
3. The cost center should be fetched from PR print UDS
4. The logic for HOD and Department columns are changed in inspection intimation slip
5. The logic for Department column is changed in inspection report (annexture)

[Inspection.Intimation.Slip.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6911066/Inspection.Intimation.Slip.PFS.v1.1.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed, please do the correction as per the PFS

As per client's request, the following points are updated in PFS

The inspection intimation slip and inspection report (annexture) should be in seperate sheets.
The inspection intimation slip should be in portrait mode and inspection report (annexture) should be in landscape mode.
The cost center should be fetched from PR print UDS
The logic for HOD and Department columns are changed in inspection intimation slip (new logic change)
The logic for Department column is changed in inspection report (annexture) (new logic change)

**Comment by Narendiranath** [comment]
Hi,
 
   As we discussed Please update the PFS & go review with Raju sir.

Regards,
Naren

**Comment by eafaisal** [comment]
@Narendiranath 

As discussed with senthil, the Work Group and Department are same.
So the HOD and Department fields should be fetched from Department column IN HRMS table as mentioned in PFS.
[Inspection.Intimation.Slip.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6952303/Inspection.Intimation.Slip.PFS.v1.2.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

             Changes are done. Kindly check. PFA Latest Deliverables & Test Result for your ref.

[Deliverable V.6.zip](https://github.com/astpl1998/PPN-Power/files/6974879/Deliverable.V.6.zip)
[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6974881/Test_Result.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
Testing is completed
[Testing2_Test_Result_Inspection.Intimation_Slip.pdf](https://github.com/astpl1998/PPN-Power/files/7184144/Testing2_Test_Result_Inspection.Intimation_Slip.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Mr.Vadivel Rajan from PPN agreed to deploy this report today (17.09.2021) by phone call.

PFS:[Inspection.Intimation.Slip.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7184289/Inspection.Intimation.Slip.PFS.v1.2.xlsx)
Latest Deliverables: [Deliverable.V.6.zip](https://github.com/astpl1998/PPN-Power/files/7184293/Deliverable.V.6.zip)
Test Case 1: [Test.Cases_Inspection.Intimation.xlsx](https://github.com/astpl1998/PPN-Power/files/7184301/Test.Cases_Inspection.Intimation.xlsx)
Test Result 1: [Test.Result_Inspection.Intimation.pdf](https://github.com/astpl1998/PPN-Power/files/7184304/Test.Result_Inspection.Intimation.pdf)
Test Case 2 :[Testing2_Test_Case_Inspection.Intimation_Slip.xlsx](https://github.com/astpl1998/PPN-Power/files/7184314/Testing2_Test_Case_Inspection.Intimation_Slip.xlsx)
Test Result 2: [Testing2_Test_Result_Inspection.Intimation_Slip.pdf](https://github.com/astpl1998/PPN-Power/files/7184319/Testing2_Test_Result_Inspection.Intimation_Slip.pdf)
 
The activity name should be **'Inspection Intimation Slip'**.
Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this report in live server.

**Comment by eafaisal** [comment]
@Narendiranath 

As discussed, the logic change for **Date** field is updated in PFS.
[Inspection.Intimation.Slip.PFS.v1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/7216634/Inspection.Intimation.Slip.PFS.v1.3.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

           Report deployed in Live server.  Kindly check. PFA Latest Deliverables for your ref.

[PPNE-94  new1.zip](https://github.com/astpl1998/PPN-Power/files/7217838/PPNE-94.new1.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
