### ISSUE TITLE
P&S-Material Discrepancy Report

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#5]
@Team,
Customer Format,
![Material Discrepancy Report print](https://user-images.githubusercontent.com/38855380/108487750-9b9fd880-72c5-11eb-8b32-06fb25de3b86.jpeg)

**Comment by Senthilmurugan-B** [comment]
@AkashGleen 
Kindly start the PFS

**Comment by AkashGleen** [comment]
Dear Senthilmurugan

I Need Clarification to the Material Discrepancy PFS Kindly Review the PFS.

1.Advised
2.Received
3.Accepted
4.Shortage
5.Rejected
6.Delivery Challan No
7.Transporter

[Material Discrepancy PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6033876/Material.Discrepancy.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Material Discrepancy Report PFS as been Completed. Kindly Move on Nxt Level

[Material Discrepancy PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6053819/Material.Discrepancy.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development as per the PFS

**Comment by BalaramanM** [comment]
EDK completed,
Rtrack Ticket raised for P&S -Material DIscrepancy Report.Ticket ID is : PPNE-45.

**Comment by BalaramanM** [comment]
@eafaisal 
As i discussed with senthil bro ,we need a clarification for column "EXCESS" 
kindly check and revert back

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

For the column "Excess" the value is given in actual test format.
The columns "Transporter" and "Inspection Remarks" are updated.
It was reviewd by Senthil.
Updated PFS: [Material.Discrepancy.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6647245/Material.Discrepancy.PFS.v1.1.xlsx)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Development completed .kindly check and revert back

Regards,
Balaraman

**Comment by eafaisal** [comment]
The Rtrack PPNE-104 was raised for wrong value in Remarks field in multi line while creating the GRN.

Regards,
Faisal

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
The logic for 'Excess' column is changed.
It will be fed manually by user.
PFS is updated.

[Material.Discrepancy.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6693132/Material.Discrepancy.PFS.v1.2.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@BalaramanM 

In GRN for the 'Transporter' field no value is given.
But it's fetching wrong value from 'Inspection Remarks'(Column 19).
Kindly check in print,attached.

[Material.Discrepancy test result 1.pdf](https://github.com/astpl1998/PPN-Power/files/6694352/Material.Discrepancy.test.result.1.pdf)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Changes are done .Kindly check and revert back
Regards,
Balaraman

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by eafaisal** [comment]
@BalaramanM 

The following issues are noted in print.

1. The text in 'Transporter' filed is not coming fully in print.
2. The Inspection Remarks column fetches the same text in print,eventhough it's different for items.

[material discrepancy-Test Result-2.pdf](https://github.com/astpl1998/PPN-Power/files/6700747/material.discrepancy-Test.Result-2.pdf)

Kindly check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
the above mentioned issues are resolved now.Kindly check and revert back
![Screenshot (164)](https://user-images.githubusercontent.com/80749490/123076440-c5653980-d436-11eb-9fa5-17fd32fbb87b.png)
Regards,
Balaraman M

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by viki18790** [comment]
@eafaisal 

Please find attached the Test Case and Test Result of Material Discrepancy Report 
[Test Result_Testing1_Material Discrepancy Report.pdf](https://github.com/astpl1998/PPN-Power/files/6702299/Test.Result_Testing1_Material.Discrepancy.Report.pdf)
[Testing1_Test_Case_Material Discrepancy Report.xlsx](https://github.com/astpl1998/PPN-Power/files/6702300/Testing1_Test_Case_Material.Discrepancy.Report.xlsx)

Regards, 

Viignesh S

**Comment by eafaisal** [comment]
@BalaramanM 

The following issues were found out in print out
1. Supplier name and address are wrong
2. Rejected quantity is wrong for second item
3. Inspection remarks is wrong for second item

The error are highlighted in print out.
Kindly check.

[Mat_Disc_Report.pdf](https://github.com/astpl1998/PPN-Power/files/6708103/Mat_Disc_Report.pdf)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Error resolved now .Kindly check and confirm
![Screenshot (165)](https://user-images.githubusercontent.com/80749490/123257739-2f9ddd00-d510-11eb-9aa5-5afd072efd48.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

1. The report should be in landscape mode (Kindly refer the attached customer format)
2. The spelling mistakes 'Tirucadaiyur' and phone number '287284' are corrected in PFS.

Updated PFS: [Material.Discrepancy.PFS.v1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/6716633/Material.Discrepancy.PFS.v1.3.xlsx)

Kindy check.

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Changes are done .Kindly check 
![Screenshot (167)](https://user-images.githubusercontent.com/80749490/123500740-cf1cb600-d65d-11eb-9ef0-13340abb9892.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_Material_Discrepancy_Report.xlsx](https://github.com/astpl1998/PPN-Power/files/6720089/Testing2_Test_Case_Material_Discrepancy_Report.xlsx)
Test Result: [Testing2_Test_Result_Material_Discrepancy_Report.pdf](https://github.com/astpl1998/PPN-Power/files/6720090/Testing2_Test_Result_Material_Discrepancy_Report.pdf)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Pls find the attached latest deliverables
[Material Discrepancy Report.zip](https://github.com/astpl1998/PPN-Power/files/6723540/Material.Discrepancy.Report.zip)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Client has given the confirmation for this report.(Mail date 16/17/2021)
Kindly move to development to deploy.

PFS: [Material.Discrepancy.PFS.v1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/6834467/Material.Discrepancy.PFS.v1.3.xlsx)
Latest Deliverables: [Material.Discrepancy.Report.zip](https://github.com/astpl1998/PPN-Power/files/6834470/Material.Discrepancy.Report.zip)
Test Case 1: [Testing1_Test_Case_Material.Discrepancy.Report.xlsx](https://github.com/astpl1998/PPN-Power/files/6834477/Testing1_Test_Case_Material.Discrepancy.Report.xlsx)
Test Result 1: [Testing1_Test_Result_Material_Discrepancy_Report.pdf](https://github.com/astpl1998/PPN-Power/files/6834478/Testing1_Test_Result_Material_Discrepancy_Report.pdf)
Test Case 2: [Testing2_Test_Case_Material_Discrepancy_Report.xlsx](https://github.com/astpl1998/PPN-Power/files/6834481/Testing2_Test_Case_Material_Discrepancy_Report.xlsx)
Test Result 2: [Testing2_Test_Result_Material_Discrepancy_Report.pdf](https://github.com/astpl1998/PPN-Power/files/6834482/Testing2_Test_Result_Material_Discrepancy_Report.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this development in Live Server

**Comment by BalaramanM** [comment]
@eafaisal bro,
Development completed in live server.Kindly check and revert back

Regards,
Balaraman M

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket.
