### ISSUE TITLE
P&S- Goods Return To Vendor Print

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#6]
@Team,
customer Format
![SRV ](https://user-images.githubusercontent.com/38855380/108488459-6ba50500-72c6-11eb-877e-6c647a56712c.jpeg)

**Comment by Senthilmurugan-B** [comment]
@AkashGleen ,
Kindly Start the PFS.

**Comment by AkashGleen** [comment]
Dear Senthilmurugan

I Need Clarification to the Stores Return Voucher PFS Kindly Review the PFS.

1.Cost Code
2.Account Code
3.Ref Doc No
4.Txn Type
5.Cost Code desc
6.Account Code desc
7.Reason For Return

[Store Return Voucher PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6033919/Store.Return.Voucher.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by Senthilmurugan-B** [comment]
@akash, 
kindly ignore the previous fromat, refer new customer format 
![GRV Letter Print](https://user-images.githubusercontent.com/38855380/109102707-71c83500-774f-11eb-9c0d-220e2d621c82.jpeg)

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Goods Return To Vendor Print PFS as been Completed. Kindly Move on Nxt Level

[Goods Return To Vendor PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6053814/Goods.Return.To.Vendor.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by AkashGleen** [comment]
Dear Raju Sir 

Goods Return To Vendor Print PFS as discuss Some Corrections will corrected & Update Completed

[Goods.Return.To.Vendor.PFS.v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6146706/Goods.Return.To.Vendor.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development as per the PFS

**Comment by Narendiranath** [comment]
Hi Akash,

             Development Completed. Kindly check. PFA Latest deliverables & Test result.

[Deliverable V.1.zip](https://github.com/astpl1998/PPN-Power/files/6472516/Deliverable.V.1.zip)

[Goods_Return_To_Vendor_Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6472517/Goods_Return_To_Vendor_Test_Result.pdf)

Thanks,
Naren

**Comment by eafaisal** [comment]
@Narendiranath 

The highlighted check box options can be removed from UDS.
The customer will manullay select the option in printed report.

Updated PFS: [Goods.Return.To.Vendor.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6505910/Goods.Return.To.Vendor.PFS.v1.1.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the modification as per the latest PFS

**Comment by Narendiranath** [comment]
@karthikeyanamitysoft 

 Rtrack raised for P&S- Goods Return To Vendor Print Ticket ID - PPNE-98

**Comment by Narendiranath** [comment]
Hi Faisal,
    
        The highlighted check box options is removed from UDS. Kindly check & Revert back. PFA Latest Deliverable & Screenshot for your ref.

[Deliverable V.2.zip](https://github.com/astpl1998/PPN-Power/files/6646155/Deliverable.V.2.zip)

![image](https://user-images.githubusercontent.com/59695578/121851454-c6e28380-cd0b-11eb-8a77-57a092e29fa9.png)

Regards,
Naren

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly start the testing 1

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 has been completed

[Test Cases_Goods Return.xlsx](https://github.com/astpl1998/PPN-Power/files/6653792/Test.Cases_Goods.Return.xlsx)
[Test Result_GRN.pdf](https://github.com/astpl1998/PPN-Power/files/6653793/Test.Result_GRN.pdf)

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_GRV.xlsx](https://github.com/astpl1998/PPN-Power/files/6655348/Testing2_Test_Case_GRV.xlsx)
Test Result: [Testing2_Test_Result_GRV.pdf](https://github.com/astpl1998/PPN-Power/files/6655351/Testing2_Test_Result_GRV.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer agreed this report to deploy in live server.(Ref: **Report status as on 17.09.2021 updated** file in email dated 20.09.2021)

![image](https://user-images.githubusercontent.com/65998153/134142836-875fd10c-aab7-44ce-aa18-efbdb37d8477.png)

PFS: [Goods.Return.To.Vendor.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/7201852/Goods.Return.To.Vendor.PFS.v1.1.xlsx)
Latest Deliverables: [Deliverable.V.2.zip](https://github.com/astpl1998/PPN-Power/files/7201856/Deliverable.V.2.zip)
 Test Case 1: [Test.Cases_Goods.Return.xlsx](https://github.com/astpl1998/PPN-Power/files/7201858/Test.Cases_Goods.Return.xlsx)
Test Result 1: [Test.Result_GRN.pdf](https://github.com/astpl1998/PPN-Power/files/7201863/Test.Result_GRN.pdf)
Test Case 2:  [Testing2_Test_Case_GRV.xlsx](https://github.com/astpl1998/PPN-Power/files/7201869/Testing2_Test_Case_GRV.xlsx)
Test Result 2: [Testing2_Test_Result_GRV.pdf](https://github.com/astpl1998/PPN-Power/files/7201876/Testing2_Test_Result_GRV.pdf)
 
Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this report in live server.

**Comment by Narendiranath** [comment]
Hi Faisal,

               Report Deployed in Live Server. Kindly check. PFA Latest Deliverables for your ref.

[Deliverable V.3.zip](https://github.com/astpl1998/PPN-Power/files/7235828/Deliverable.V.3.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup SIr,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
