### ISSUE TITLE
RM-Scrap Invoice Print

### ISSUE THREAD

**Issue by AkashGleen** [astpl1998/PPN-Power#64]
@team

[JV _54 scrap sale.pdf](https://github.com/astpl1998/PPN-Power/files/6179482/JV._54.scrap.sale.pdf)

**Comment by AkashGleen** [comment]
@eafaisal 

Kindly Start The Scrap Sale Invoice Print PFS

**Comment by eafaisal** [comment]
Customer format is attached
![scrap_sale_invoice](https://user-images.githubusercontent.com/65998153/117527929-2eaafd80-afed-11eb-8a36-16d44cc5f14d.jpg)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

PFS is completed.Kindly move to next level.

[Scrap_Invoice_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6560838/Scrap_Invoice_Print.xlsx)


Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this print out.

**Comment by eafaisal** [comment]
@adlinmanna 

Tax values are corrected in column level requirements.
Updated PFS: [Scrap_Invoice_Print_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6642142/Scrap_Invoice_Print_V1.1.xlsx)

Regards,
Faisal

**Comment by adlinmanna** [comment]
Development Completed.
[Scrap_Sale_Invoice_Report.pdf](https://github.com/astpl1998/PPN-Power/files/6670630/Scrap_Sale_Invoice_Report.pdf)
Kindly check and revert back.

Regards,
Adlin Manna

**Comment by eafaisal** [comment]
@JESTIN26 

Kindy do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@adlinmanna 

In testing the following issues are noted.
1. The date format is wrong.
2. There is more space in print below items table.The print should be in one page.

Kindly check the print out in attachment.
[Test Result_Scrap invoice.pdf](https://github.com/astpl1998/PPN-Power/files/6677096/Test.Result_Scrap.invoice.pdf)

Regards,
Faisal

**Comment by adlinmanna** [comment]
Corrections done.

Kindly check.
[Scrap_Sale_Invoice_Report_1.pdf](https://github.com/astpl1998/PPN-Power/files/6680805/Scrap_Sale_Invoice_Report_1.pdf)

Regards,
Adlin Manna

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again.

Regards,
Faisal

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 has been completed

[Test Resul_Scrap Invoice.pdf](https://github.com/astpl1998/PPN-Power/files/6684917/Test.Resul_Scrap.Invoice.pdf)
[Test cases_Scrap invoice.xlsx](https://github.com/astpl1998/PPN-Power/files/6684919/Test.cases_Scrap.invoice.xlsx)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case:[Testing2_Test_Case_Scrap_Invoice_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6685576/Testing2_Test_Case_Scrap_Invoice_Print.xlsx)
Test Result: [Testing2_Test_Result_Scrap_Invoice_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6685580/Testing2_Test_Result_Scrap_Invoice_Print.pdf)

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal,

PFA the latest deliverables.

[PPNE-97.zip](https://github.com/astpl1998/PPN-Power/files/6727836/PPNE-97.zip)

Thanks,
Adlin

**Comment by adlinmanna** [comment]
@eafaisal ,

Development rework changes completed.
[Scrap_Invoice_Print_2.pdf](https://github.com/astpl1998/PPN-Power/files/7093768/Scrap_Invoice_Print_2.pdf)
Kindly check and revert back.

Regards,
Adlin

**Comment by eafaisal** [comment]
Testing is completed.
Test result is attached.
[Testing2.Test.Case.Scrap.Invoice.pdf](https://github.com/astpl1998/PPN-Power/files/7096698/Testing2.Test.Case.Scrap.Invoice.pdf)

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal,

Please find the latest deliverables.
[PPNE-97 - Dev Rework.zip](https://github.com/astpl1998/PPN-Power/files/7096863/PPNE-97.-.Dev.Rework.zip)

Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer agreed the report to deploy in live server through email.

![image](https://user-images.githubusercontent.com/65998153/132448152-fe3c0d00-2650-4463-9099-2c73e2dec9c1.png)

PFS: [Scrap_Invoice_Print_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7125950/Scrap_Invoice_Print_V1.2.xlsx)
Latest Deliverables: [PPNE-97.-.Dev.Rework (1).zip](https://github.com/astpl1998/PPN-Power/files/7125953/PPNE-97.-.Dev.Rework.1.zip)
Test Case 1: [Test.cases_Scrap.invoice.xlsx](https://github.com/astpl1998/PPN-Power/files/7125955/Test.cases_Scrap.invoice.xlsx)
Test Result 1: [Test.Resul_Scrap.Invoice.pdf](https://github.com/astpl1998/PPN-Power/files/7125958/Test.Resul_Scrap.Invoice.pdf)
Test Case 2: [Testing2_Test_Case_Scrap_Invoice_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/7125960/Testing2_Test_Case_Scrap_Invoice_Print.xlsx)
Test REsult 2: [Testing2_Test_Report_Scrap_Invoice_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7125962/Testing2_Test_Report_Scrap_Invoice_Print.pdf)

Kindly move to development to deploy.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server and please attach the deliverables in this github

**Comment by adlinmanna** [comment]
@eafaisal ,

Deliverables deployed in live server. Please check and revert back.

Please find the latest deliverables.
[PPNE-97 - Dev Rework.zip](https://github.com/astpl1998/PPN-Power/files/7139585/PPNE-97.-.Dev.Rework.zip)

Regards,
Adlin

**Comment by eafaisal** [comment]
@adlinmanna 

While printing the invoice it's showing "The report file scrap_sale_invoice is not deployed in Ramco DecisionWorks Application" error.
Kindly check.

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal ,

I have deployed in live server. Please check and revert back.

Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
