### ISSUE TITLE
PM-Direct Invoice TDS Calculation Trigger

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#66]
@Team 
Need clarification from client on include and exclude the types of TCD's.
once clarified will update the logic

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir : 
PFS :  [PFS-Direct Invoice TDS Calculation Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/6732725/PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this trigger to change the taxable amount in the TDS column.

**Comment by adlinmanna** [comment]
@Senthilmurugan-B  ,

Please provide proper input data.

Regards,
Adlin

**Comment by Senthilmurugan-B** [comment]
Updated PFS : 
[Uploading Updated PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx…]()

**Comment by Senthilmurugan-B** [comment]
@adlinmanna 
Updated PFS : 
[Updated PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/6768287/Updated.PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx)

**Comment by adlinmanna** [comment]
@Senthilmurugan-B ,

Trigger created.
Kindly check and revert back.

Regards,
Adlin

**Comment by Senthilmurugan-B** [comment]
@eafaisal 
Testing 1 completed, kindly do the testing 2
![Test Result_1 for Direct Invoice TDS Calculation Trigger](https://user-images.githubusercontent.com/38855380/124888626-e52e5d00-dff3-11eb-9734-5fe317226720.jpg)
[Test Case_1 for Direct Invoice TDS Calculation Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/6782889/Test.Case_1.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx)

**Comment by eafaisal** [comment]
Testing 2 is completed.

![image](https://user-images.githubusercontent.com/65998153/124898423-ce403880-dffc-11eb-945c-20f21162dda9.png)

[Test.Case_2.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/6783310/Test.Case_2.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx)

**Comment by adlinmanna** [comment]
PFA the trigger SQL.
[Trigger_sql.zip](https://github.com/astpl1998/PPN-Power/files/6834195/Trigger_sql.zip)


Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The customer agreed this report (Mail date: 25.08.2021)
Kindly move to deploy in live server.

PFS: [Updated.PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/7070188/Updated.PFS-Direct.Invoice.TDS.Calculation.Trigger.xlsx)
Latest Deliverables: [Trigger_sql.zip](https://github.com/astpl1998/PPN-Power/files/7070190/Trigger_sql.zip)
Test Case 1: [Test.Case_1.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/7070192/Test.Case_1.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx)
Test Result 1: 
![Testing1 TDS Trigger](https://user-images.githubusercontent.com/65998153/131207386-b3f47205-f28e-4c37-a0a4-3d5b8a39e7ce.jpg)
Test Case 2: [Test.Case_2.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx](https://github.com/astpl1998/PPN-Power/files/7070194/Test.Case_2.for.Direct.Invoice.TDS.Calculation.Trigger.xlsx)
Test Result 2: ![Testing2 TDS Trigger](https://user-images.githubusercontent.com/65998153/131207413-fa7fe0d7-daec-4572-ad7e-1e1476138355.jpg)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this trigger from test server to live server

**Comment by adlinmanna** [comment]
Deployed in live server.

Please find attached the latest Deliverables.
[Trigger_sql.zip](https://github.com/astpl1998/PPN-Power/files/7103696/Trigger_sql.zip)


Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The deployment is completed.
Customer told that it was working correctly on phone call on 04.09.2021
Kindly close the ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Development completed, so closing this ticket
