### ISSUE TITLE
P&S-Request For Quotation Print Out

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#67]
@eafaisal,
Kindly update the customer format and start the PFS

**Comment by eafaisal** [comment]
Customer format

![Request for Quotation](https://user-images.githubusercontent.com/65998153/122743312-843d2000-d2a4-11eb-9634-c63efeb1e484.jpeg)

**Comment by eafaisal** [comment]
@raju-kurup 

PFS is completed.
Kindly move to next level.

[Request_for_Quotation_V1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6691844/Request_for_Quotation_V1.0.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop as per the PFS attached

**Comment by eafaisal** [comment]
@adlinmanna 

The PFS is updated.

[Request_for_Quotation_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6699566/Request_for_Quotation_V1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@adlinmanna 

The supplier code field is added in UDS.
Updated PFS: [Request_for_Quotation_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6715747/Request_for_Quotation_V1.2.xlsx)

Regards,
Faisal

**Comment by adlinmanna** [comment]
Development Completed.

[Request for Quotation.pdf](https://github.com/astpl1998/PPN-Power/files/6756696/Request.for.Quotation.pdf)
Kindly check and revert back.

Regards,
Adlin Manna

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@adlinmanna 

The following issues were found in RFQ print.

1. Date and Due Date are interchanged
2. Required Qty is missing for third item

[RFQ.pdf](https://github.com/astpl1998/PPN-Power/files/6758307/RFQ.pdf)

KIndly check.

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal ,

Corrections done.
[Request for Quotation.pdf](https://github.com/astpl1998/PPN-Power/files/6765637/Request.for.Quotation.pdf)

Regards,
Adlin Manna

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again.

Regards,
Faisal

**Comment by eafaisal** [comment]
@adlinmanna 

The address in footer is missing in second page.
The footer address should be in all pages.
Kindly check.

[Test Result_RFQ.pdf](https://github.com/astpl1998/PPN-Power/files/6783676/Test.Result_RFQ.pdf)

Regards,
Faisal

**Comment by karthikeyanamitysoft** [comment]
adlin as we discussed move that address part into pagefooter.

**Comment by adlinmanna** [comment]
@eafaisal ,

Page Footer changes done.
[RFQ.pdf](https://github.com/astpl1998/PPN-Power/files/6791059/RFQ.pdf)

Regards,
Adlin

**Comment by eafaisal** [comment]
@JESTIN26 

Kindly do the test again.

**Comment by JESTIN26** [comment]
@eafaisal 

Testing 1 has been completed

[Test Result_RFQ.pdf](https://github.com/astpl1998/PPN-Power/files/6794639/Test.Result_RFQ.pdf)
[Test Cases_RFQ.xlsx](https://github.com/astpl1998/PPN-Power/files/6794640/Test.Cases_RFQ.xlsx)

**Comment by eafaisal** [comment]
@Testing 2 is completed.

Test Case: [Testing2_Test_Case_RFQ_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6795165/Testing2_Test_Case_RFQ_Print.xlsx)
Test Result: [Testing2_Test_Result_RFQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6795166/Testing2_Test_Result_RFQ_Print.pdf)

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal ,

Latest deliverables.
[PPNE-110.zip](https://github.com/astpl1998/PPN-Power/files/6834186/PPNE-110.zip)

Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Client has given confirmation for this report. (Mail date 16/07/2021)
Kindly move this report to development to deploy.

PFS: [Request_for_Quotation_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6834678/Request_for_Quotation_V1.2.xlsx)
Latest Deliverables: [PPNE-110.zip](https://github.com/astpl1998/PPN-Power/files/6834679/PPNE-110.zip)
Test Case 1: [Testing1_Test_Case_RFQ_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6834681/Testing1_Test_Case_RFQ_Print.xlsx)
Test Result 1: [Testing1_Test_Result_RFQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6834682/Testing1_Test_Result_RFQ_Print.pdf)
Test Case2: [Testing2_Test_Case_RFQ_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6834684/Testing2_Test_Case_RFQ_Print.xlsx)
Test Result 2: [Testing2_Test_Result_RFQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/6834686/Testing2_Test_Result_RFQ_Print.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please move this development to Live Server.

**Comment by adlinmanna** [comment]
@eafaisal ,

Development moved to live server.
Please check and revert back.

Regards,
Adlin

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket.

**Comment by eafaisal** [comment]
@adlinmanna 

There are two issues in print out.
1. The date is not fully printed.
2. The item description is not fully printed.

The print out is attached
[RFQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7235723/RFQ_Print.pdf)

Kindly check.

Regards,
Faisal

**Comment by adlinmanna** [comment]
@eafaisal ,

Issues fixed. As discussed fixes deployed in UAT and live server.
Please find attached the report and latest deliverables.
[RFQ_Print_Dev_Rework.pdf](https://github.com/astpl1998/PPN-Power/files/7243361/RFQ_Print_Dev_Rework.pdf)
[RFQ_Print_Dev_Rework_Live.pdf](https://github.com/astpl1998/PPN-Power/files/7243362/RFQ_Print_Dev_Rework_Live.pdf)
[PPNE-110.zip](https://github.com/astpl1998/PPN-Power/files/7243379/PPNE-110.zip)

Regards,
Adlin

**Comment by eafaisal** [comment]
Testing is completed.
[Test.Result_RFQ_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7243489/Test.Result_RFQ_Print.pdf)

**Comment by eafaisal** [comment]
@raju-kurup SIr,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Accepted by customer and deployed in live server, so closing this ticket
