### ISSUE TITLE
IMP-EMOD (Enterprise Modelling) - SDD Sign Off

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#68]
SDD for Enterprises Modelling - Sign off 

Sign off  :
[EMOD Sign off.pdf](https://github.com/astpl1998/PPN-Power/files/6719725/EMOD.Sign.off.pdf)

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir,
we received the EMOD SDD sign Off from PPN
[EMOD-Enterprise Modeling Structure.pdf](https://github.com/astpl1998/PPN-Power/files/6723609/EMOD-Enterprise.Modeling.Structure.pdf)
Kindly check and close the ticket

**Comment by raju-kurup** [comment]
Sign off received from Customer so closing this issue
