### ISSUE TITLE
IMP-Finance and Accounts - SDD Sign OFF

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#69]
Sign off document from PPN for Finance and Accounts

Sign off Document : 

SDD received from Customer after reviewing
[PPN_Book Keeping_SDD_v1.0.docx](https://github.com/astpl1998/PPN-Power/files/6719750/PPN_Book.Keeping_SDD_v1.0.docx)
[PPN_Global Tax Solutions_SDD.docx](https://github.com/astpl1998/PPN-Power/files/6719751/PPN_Global.Tax.Solutions_SDD.docx)
[PPN_Management Accounting_SDD.docx](https://github.com/astpl1998/PPN-Power/files/6719752/PPN_Management.Accounting_SDD.docx)
[PPN_Payable Managment _SDD_v1.0.docx](https://github.com/astpl1998/PPN-Power/files/6719753/PPN_Payable.Managment._SDD_v1.0.docx)
[PPN_Receivable Management_SDD.docx](https://github.com/astpl1998/PPN-Power/files/6719754/PPN_Receivable.Management_SDD.docx)

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir: 
SDD Sign Off Documents receied from PPN
[Book Keeping.pdf](https://github.com/astpl1998/PPN-Power/files/6723470/Book.Keeping.pdf)
[Global Tax Solutions.pdf](https://github.com/astpl1998/PPN-Power/files/6723472/Global.Tax.Solutions.pdf)
[Management Accounting.pdf](https://github.com/astpl1998/PPN-Power/files/6723473/Management.Accounting.pdf)
[Payable Management.pdf](https://github.com/astpl1998/PPN-Power/files/6723474/Payable.Management.pdf)
[Receivables Management.pdf](https://github.com/astpl1998/PPN-Power/files/6723475/Receivables.Management.pdf)

Fixed Asset Pending

**Comment by raju-kurup** [comment]
Being sign off received we are closing this ticket
