### ISSUE TITLE
P&S- PO  Forwarding letter

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#7]
@Team,
Customer Format,
![PO forwarding Letter ](https://user-images.githubusercontent.com/38855380/108949508-8db5d300-768a-11eb-9e30-154eb93ed21c.jpeg)

**Comment by Senthilmurugan-B** [comment]
@Faisal,
Kindly start the PFS.

**Comment by faisal** [comment]
Do you mean someone else?

**Comment by astpl1998** [comment]
Dear Mr Faisal N Jawdat

 

There seems to be a wrong mapping we will ensure this will not happen in future 

 

Regret for the inconvenience 

 

Regards

Suressh.CG                      



Head - ERP Practice

Certifications: Certified RamcoERP Consultant- (Finance, Supplychain, Production, Enterprise Asset Management)

AmitySoft Technologies Pvt Ltd.,

Email:  <mailto:sharmilabk@amitysoft.in> suressh@amitysoft.com | Mobile: +91-9790789979

Telephone :+91-044 42035577 / 24328077

Skype: suressh.cg LinkedIn: suressh@amitysoft.com <mailto:suressh@amitysoft.com>  Twitter : @suresshcg

HO: 6/22,II Floor, Dhandapani Street, T.Nagar, Chennai - 600 017, India

Offices : Bangalore, Mumbai, Vadodara, Kochi.

 <https://www.facebook.com/Amitysofttechnologiespvtltd>   <https://www.linkedin.com/in/amitysoft-technologies-a6201a161/>   <https://twitter.com/AmitysoftTechno>   <https://www.youtube.com/user/Amitysoft1998/videos>  |  <http://www.amitysoft.com/> www.amitysoft.com

Enterprise Solutions: ERP, Data Analytics, IoT

Advisory & Technical Services: Enterprise Cyber Security, Quality Assurance & Testing,

Functional Sizing, CMMI/ISO

Training: Testing, Software Quality Management, Big Data, Info Security, ERP

Disclaimer: The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorized. If you have received this communication in error, please address with the subject heading "Received in error," send to info@amitysoft.com <mailto:info@amitysoft.com> , then delete the e-mail and destroy any copies of it. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any opinions or advice contained in this e-mail are subject to the terms and conditions expressed in the governing agreement between Amitysoft and the client. Opinions, conclusions and other information in this e-mail and any attachments that do not relate to the official business of Amitysoft Technologies are neither given nor endorsed by it.

 

Amitysoft Technologies cannot guarantee that the e-mail communications are secure or error-free, as information could be intercepted, corrupted, amended, lost, destroyed, arrive late or incomplete, or contain viruses.

**Comment by eafaisal** [comment]
Sir,

PO Forwarding Letter is completed.
Kindly move to development.

[PO_Forwarding_Letter.xlsx](https://github.com/astpl1998/PPN-Power/files/6054024/PO_Forwarding_Letter.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
Sir,

Updated PFS is attached.

[PO_Forwarding_Letter_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6100653/PO_Forwarding_Letter_V1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
[PO_Forwarding_Letter_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6101484/PO_Forwarding_Letter_V1.1.xlsx)

updated PFS

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report with UDS

**Comment by karthikeyanamitysoft** [comment]
Dear BHarathi,

Kindly start new development for the attached PFS.

Regareds,
Karthi

**Comment by BalaramanM** [comment]
Development completed .Kindly check and revert back

**Comment by BalaramanM** [comment]
[PPNE-76.zip](https://github.com/astpl1998/PPN-Power/files/6515559/PPNE-76.zip)
Deliverables added.Kindly check

**Comment by Senthilmurugan-B** [comment]
@SHIBY46 
Kindly start the testing 1

**Comment by eafaisal** [comment]
@BalaramanM 

The values in column 'Value (Rs) incl' are not fetched from UDS of 'Recommendation for PO approval' report.
Kindly check in the print,attached.
[PO_FOr_let.pdf](https://github.com/astpl1998/PPN-Power/files/6522427/PO_FOr_let.pdf)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
 Now the Value (Rs) incl GST fetched from UDS of 'Recommendation for PO approval' report.
kindly check the attached print
[Uploading PO_FOr_let1.pdf…]()

**Comment by eafaisal** [comment]
@SHIBY46 

Kindly do the test again

Regards,
Faisal

**Comment by SHIBY46** [comment]
@eafaisal 

Test Case 1 Completed

[PO forwarding letter test case.pdf](https://github.com/astpl1998/PPN-Power/files/6525842/PO.forwarding.letter.test.case.pdf)
[PPN PO forwarding letter testing REPORT.xlsx](https://github.com/astpl1998/PPN-Power/files/6525843/PPN.PO.forwarding.letter.testing.REPORT.xlsx)

**Comment by eafaisal** [comment]
@mohanaamity 

The values in "Value (Rs) incl GST" column in PO forwarding letter is wrong.Kindly check.
[PO_Forwarding_Letter.pdf](https://github.com/astpl1998/PPN-Power/files/6526567/PO_Forwarding_Letter.pdf)

It's not fetching the actual values given in UDS in Recommendation of PO approval

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
the error resolved now.Kindly check

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_PO_Forwarding_Letter.xlsx](https://github.com/astpl1998/PPN-Power/files/6526729/Testing2_Test_Case_PO_Forwarding_Letter.xlsx)
Test Result: 
[Testing2_Test_Result_PO_Forwarding_Letter.pdf](https://github.com/astpl1998/PPN-Power/files/6526731/Testing2_Test_Result_PO_Forwarding_Letter.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Client has given confirmation for this report.
Kindly check and move to live server.

PFS: [PFS.PO_Forwarding_Letter_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6774493/PFS.PO_Forwarding_Letter_V1.1.xlsx)
Latest Deliverables: [PPNE-76 (1).zip](https://github.com/astpl1998/PPN-Power/files/6774495/PPNE-76.1.zip)
Testing1 Test Case: [Testing1_Test_Case_PO_Forwarding_Letter.xlsx](https://github.com/astpl1998/PPN-Power/files/6774501/Testing1_Test_Case_PO_Forwarding_Letter.xlsx)
Testing1 Test Result: [Testing1_Test_Result_PO_Forwarding_Letter.pdf](https://github.com/astpl1998/PPN-Power/files/6774505/Testing1_Test_Result_PO_Forwarding_Letter.pdf)
Testing2 Test Case: [Testing2_Test_Case_PO_Forwarding_Letter.xlsx](https://github.com/astpl1998/PPN-Power/files/6774509/Testing2_Test_Case_PO_Forwarding_Letter.xlsx)
Testing2 Test Result: [Testing2_Test_Result_PO_Forwarding_Letter (1).pdf](https://github.com/astpl1998/PPN-Power/files/6774515/Testing2_Test_Result_PO_Forwarding_Letter.1.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this ticket from Test to Live Server

**Comment by BalaramanM** [comment]
Development completed .While clicking print button in live server error thown like "Service XML file error".Rised Rtrack for regarding that issue .Once solution is provided i will do needful

Regards,
Balaraman

**Comment by BalaramanM** [comment]
@eafaisal bro
Development completed in live server .Kindly check and revert back


Regards,
Balaraman M

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per client's requirement the following changes need to be done.
1. If it's amended PO, the **Amendment No** also should be printed with PO No.
2. The lenght of **Payment Terms** column need to be increased to Maximum 150 characters.
The PFS is updated.
[PFS.PO_Forwarding_Letter_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7160790/PFS.PO_Forwarding_Letter_V1.2.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : 2 points to be attended in this report.
1. PO Number with Amendment should come. This is new logic change
2. Payterm column width to be increased.

**Comment by BalaramanM** [comment]
@eafaisal bro
The above mentioned changes are done as per updated PFS.Kindly check and confirm
![Screenshot (275)](https://user-images.githubusercontent.com/80749490/133884211-d1988abc-d591-41fa-959c-d8b1ecea5e9f.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
@BalaramanM 

The **Amendment No** and **Payment Terms** fields are fetched correctly.
But the values in **Value (Rs) incl GST** field is wrong.
Kindly refer the attached print out.
[POF.pdf](https://github.com/astpl1998/PPN-Power/files/7189761/POF.pdf)

Regards,
Faisal

**Comment by BalaramanM** [comment]
@eafaisal 
Error resolved.Kindly check and confirm
![image](https://user-images.githubusercontent.com/80749490/133886675-f6338cbe-47dc-490e-b112-25354326aec1.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
Testing is completed
[Test.Result.PO.Forwarding.Letter.pdf](https://github.com/astpl1998/PPN-Power/files/7200672/Test.Result.PO.Forwarding.Letter.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As the **Recommendation of PO Approval** report is deloyed in **Purchase and subcontracting >>Purchase Order>>Amend Purchase order** also, the columns **Item Description** and **Value(Rs) incl GST** are updated to get values from **Purchase and subcontracting >>Purchase Order>>Amend Purchase order**
[PFS.PO_Forwarding_Letter_V1.3.xlsx](https://github.com/astpl1998/PPN-Power/files/7235470/PFS.PO_Forwarding_Letter_V1.3.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : previously UDS was deployed in edit screen only so item description and values was taken from that only.  Now we have included UDS in Amend screen also so we want to take the item description and values from Amend also.  Contact Faisal for futher clarification if any.

**Comment by BalaramanM** [comment]
@eafaisal bro
Changes are done.Kindly check
![image](https://user-images.githubusercontent.com/80749490/135216362-0c386010-8eb6-4e03-ac3b-9f71b4c23aad.png)

Regards,
Balaraman

**Comment by eafaisal** [comment]
Testing is completed.
[Testing2_Test_Result_PO_Forwarding_Letter.pdf](https://github.com/astpl1998/PPN-Power/files/7264193/Testing2_Test_Result_PO_Forwarding_Letter.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment is completed and accepted by the client through email.

![image](https://user-images.githubusercontent.com/65998153/141102178-6496db63-f93f-4cd3-b69d-9f87c23d3dcd.png)

Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
PPN Accepted and moved to live server, so closing this issue
