### ISSUE TITLE
IMP-Inventory & PICC - SDD Sign Off

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#73]

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir:
Herewith i have attached the Inventory SDD Sign Off document.
Kindly check and close the ticket.
[PPN_SDD_INVENTORY&PICC_V1.2.pdf](https://github.com/astpl1998/PPN-Power/files/6789421/PPN_SDD_INVENTORY.PICC_V1.2.pdf)

**Comment by raju-kurup** [comment]
Sign off received from customer, so closing this ticket
