### ISSUE TITLE
IMP-Sales & Shipping - SDD Sign OFF

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#74]

**Comment by Senthilmurugan-B** [comment]
@raju-kurup sir:
Herewith i have attached the Sales and shipping SDD Sign Off document.
Kindly check and close the ticket.
[SALES & SHIPPING SDD.pdf](https://github.com/astpl1998/PPN-Power/files/6789413/SALES.SHIPPING.SDD.pdf)

**Comment by raju-kurup** [comment]
Sign off received from customer, so closing this ticket
