### ISSUE TITLE
IMP-Maintenance Management - SDD Sign Off

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#75]

**Comment by Senthilmurugan-B** [comment]
@raju-kurup: 
Herewith i have attached the EAM SDD Sign Off document. 
Kindly check and close the ticket.
[PPN_SDD_EAM_V1.2 (002).pdf](https://github.com/astpl1998/PPN-Power/files/6789387/PPN_SDD_EAM_V1.2.002.pdf)

**Comment by raju-kurup** [comment]
Sign off received from customer, so closing this ticket
