### ISSUE TITLE
EAM-Extract SOG from Activity Dcube Report (Deffered)

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#8]
@Team,

In the clearance permit screen we need to extract the SOG against the Activity   (Dcube Report link tobe provide in clearance permit screen)

**Comment by Senthilmurugan-B** [comment]
@Team 
PPN will develop the DCUBE

**Comment by raju-kurup** [comment]
Being this report is deferred by customer, we are closing this ticket
