### ISSUE TITLE
ISS - EDK description to be update in the item master 

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#81]
@karthikeyanamitysoft 👍 
As we discussed kindly update description in the item master
[BLUE-167_Items With EDK Description-To Amity - Copy.xlsx](https://github.com/astpl1998/PPN-Power/files/6820577/BLUE-167_Items.With.EDK.Description-To.Amity.-.Copy.xlsx)
[GREEN-31089_Items With EDK Description-To Amity.xlsx](https://github.com/astpl1998/PPN-Power/files/6820578/GREEN-31089_Items.With.EDK.Description-To.Amity.xlsx)

**Comment by Senthilmurugan-B** [comment]
as we discussed we need to update the item description through back end for that pls refer below                                                1.GREEN COLOUR - items we need to update the description in  inventory&PICC >> item administration >> Maintain Item Quick 
                                 creation >> item information >> Item Short Desc.                                                                                                                           2.BLUE COLOUR - items we need to break the item description In to two parts                                                                        
  2a - first 500 characters need to update in inventory&PICC >> item administration >> Maintain Item Quick creation >>                           
         item information >> Item Short Desc.                                                                                                                                                           
 2B - above 500 characters need to update in inventory&PICC >> item administration >> Maintain Item Quick creation >> item 
         information >> Variant Short Desc..

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by karthikeyanamitysoft** [comment]
[green_items.zip](https://github.com/astpl1998/PPN-Power/files/6834312/green_items.zip)

**Comment by raju-kurup** [comment]
@Senthilmurugan-B : please check this

**Comment by Senthilmurugan-B** [comment]
@Raju sir: 
As per the requirement, we updated the description.
Email also send to PPN Email Ref: 20/07/202.
Kindly close the ticket.

**Comment by raju-kurup** [comment]
Updation done, so closing this ticket
