### ISSUE TITLE
PM - RTGS/NEFT Letter to Bank

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#83]

**Comment by eafaisal** [comment]
customer format is attached.
![NEFT   RTGS Bank Letter - Sample Format](https://user-images.githubusercontent.com/65998153/134619799-31dd16e0-4963-4c0c-8cbc-d5343d82b2ee.jpg)

**Comment by eafaisal** [comment]
@raju-kurup Sir,
PFS is completed.

[PFS.Letter.To.Bank_V1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/7229150/PFS.Letter.To.Bank_V1.0.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the new development as per PFS

**Comment by Narendiranath** [comment]
Hi Faisal,

           Development completed. Kindly check. PFA Latest deliverables for your ref.

[PPNE-153 -new.zip](https://github.com/astpl1998/PPN-Power/files/7446180/PPNE-153.-new.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@SHIBY46 

Kindly start the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment]
@MOHAN2212 

Kindly start the testing 1.

Regards,
Faisal

**Comment by MOHAN2212** [comment]
OK SIR

**Comment by MOHAN2212** [comment]
@eafaisal Sir,

Letter to bank testing 1 completed.

[Testing1_Test_Case_Letter Bank_Print.xlsx](https://github.com/astpl1998/PPN-Power/files/7538432/Testing1_Test_Case_Letter.Bank_Print.xlsx)
[Testing1_Test_Report_Letter Bank_Print.pdf](https://github.com/astpl1998/PPN-Power/files/7538433/Testing1_Test_Report_Letter.Bank_Print.pdf)

Regards,
Mohan

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case:[Testing2_Test_Case_Letter_to_Bank.xlsx](https://github.com/astpl1998/PPN-Power/files/7544750/Testing2_Test_Case_Letter_to_Bank.xlsx)
 Test Result: [Testing2_Test_Result_Letter_to_Bank.pdf](https://github.com/astpl1998/PPN-Power/files/7544755/Testing2_Test_Result_Letter_to_Bank.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As the customer has agreed this report, kindly move this to deploy in live server.

![image](https://user-images.githubusercontent.com/65998153/142153856-3f509b17-a94c-462c-820f-a33ef9818d6a.png)

PFS: [PFS.Letter.To.Bank_V1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/7552552/PFS.Letter.To.Bank_V1.0.xlsx)
 Latest Deliverables: [PPNE-153.-new.zip](https://github.com/astpl1998/PPN-Power/files/7552554/PPNE-153.-new.zip)
 Test Case 1: [Testing1_Test_Case_Letter.Bank_Print (1).xlsx](https://github.com/astpl1998/PPN-Power/files/7552555/Testing1_Test_Case_Letter.Bank_Print.1.xlsx)
 Test Result 1: [Testing1_Test_Report_Letter.Bank_Print (1).pdf](https://github.com/astpl1998/PPN-Power/files/7552557/Testing1_Test_Report_Letter.Bank_Print.1.pdf)
 Test Case 2: [Testing2_Test_Case_Letter_to_Bank.xlsx](https://github.com/astpl1998/PPN-Power/files/7552559/Testing2_Test_Case_Letter_to_Bank.xlsx)
 Test Result 2: [Testing2_Test_Result_Letter_to_Bank.pdf](https://github.com/astpl1998/PPN-Power/files/7552560/Testing2_Test_Result_Letter_to_Bank.pdf)
 
Regards,
Faisal

**Comment by raju-kurup** [comment]
Testing completed by us and PPN accepted, so please move this development to Live server

**Comment by Narendiranath** [comment]
Hi Faisal,

               Report deployed in live server. Kindly check . PFA Latest Deliverables for your ref.

[PPNE-153 -new.zip](https://github.com/astpl1998/PPN-Power/files/7589524/PPNE-153.-new.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Being development completed and deployed in live, we are closing this ticket.
