### ISSUE TITLE
ISS - Not able to create Supplier Account based Credit and Debit Note without Doc Reference No.

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#84]
@raju-kurup sir,

Urgent requirements need developer support to update the below said parameter through backend in PPN UAT server.

Rtrack Ref: PPNE-130

Rtrack Comment : 

Request you to check the below PPS parameters and try with your sequence:

Customer sequence:
The PPS parameter for allowing customer account based note transactions without reference document is PPS_CDCN_00001.
After changing the said parameter as No, it would be possible to authorize customer account based note.

Supplier sequence:
Once the PPS feature 'PPS_SCDN_00001' (Reference Document mandatory for Supplier Debit Credit Notes - GST India) is provided as 'No' in 'pps_finance_feature_list' table; it would be possible to authorize supplier debit credit notes without reference documents.

![image](https://user-images.githubusercontent.com/38855314/128821437-5fe51ad2-81c3-4b03-898d-92d6bfdc5de0.png)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please apply this PPS Parameter in test server immediately.

**Comment by karthikeyanamitysoft** [comment]
begin tran
update  pps_finance_feature_list set FLAG_YES_NO = 'No'where feature_id= 'PPS_CDCN_00001'
commit

**Comment by raju-kurup** [comment]
PPS feature changed in both the server and working fine.
