### ISSUE TITLE
EAM-Clearance Permit print out 

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#9]
@TEAM,
CUSTOMER FORMAT,
![CLEARANCE PERMIT](https://user-images.githubusercontent.com/38855380/108595654-09700100-73a7-11eb-82e0-f1d4b0422861.jpeg)
Kindly start the PFS

**Comment by AkashGleen** [comment]
Dear Raju Sir,

EAM-Clearance Permit Print Out PFS Completed.

[Clearnce Permits PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6148450/Clearnce.Permits.PFS.v1.0.xlsx)

Regards,
Akash

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Pl develop this report as per the PFS

**Comment by karthikeyanamitysoft** [comment]
Deaar Naren,

Kindly start the new development.

please get clarification on Data Transfer which control and which screen.
REgards,
Karthi

**Comment by Narendiranath** [comment]
Hi,

There is no check box available for using data transfer. So you can raise ticket for Ramco. Once check box will came you assign ticket for me.

![image](https://user-images.githubusercontent.com/59695578/117414565-e6c89f80-af34-11eb-95d3-0bffa43c19a4.png)

Regards,
Naren

**Comment by eafaisal** [comment]
RTrack ticket PPNE-75 raised for this issue.
https://rtrackconnect.ramco.com/browse/PPNE-75

**Comment by AkashGleen** [comment]
@Narendiranath 

Updated PFS Attached Kindly use this

[Clearnce Permits PFS v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6450272/Clearnce.Permits.PFS.v1.0.xlsx)

**Comment by Narendiranath** [comment]
Hi Akash,

Kindly give me the exact logic for below columns in this report.
1. Issue Date
2. Extended From
3. Extended To
4. Issue Authority 

Thanks,
Naren

**Comment by Senthilmurugan-B** [comment]
@Narendiranath 
Herewith i have attached the Updated PFS for your perusal
KIndly start the Development 
[Clearnce.Permits.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6529486/Clearnce.Permits.PFS.v1.1.xlsx)

**Comment by Narendiranath** [comment]
Dear Raju Sir,

                Please review the PFS & Allocate to me.

Regards,
Naren

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report with high priority

**Comment by Narendiranath** [comment]
Hi Senthil,

            Development completed. Kindly check & Revert back. PFA Latest Deliverables & Test result for your ref.

[CP_Print.zip](https://github.com/astpl1998/PPN-Power/files/6614446/CP_Print.zip)

[Test_Result.pdf](https://github.com/astpl1998/PPN-Power/files/6614448/Test_Result.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing 1

**Comment by eafaisal** [comment]
@Narendiranath 

The following errors were found in Clearance Permit print
1. The years is wrong as '02021' in 'Issue Date' filed
2. The spelling needs to be corrected as 'Description' in 'Work Discription' field
3. The value was not fetched in print for 'Eqp Description' field
4. There is only one activity printed instead of three activities in 'Activity' field
5. The value was not fetched in print for 'Component Desc' field

Kindly check.
The print is attached.
[testing-1_errors.pdf](https://github.com/astpl1998/PPN-Power/files/6623970/testing-1_errors.pdf)

Regards,
Faisal

**Comment by Narendiranath** [comment]
Hi Faisal,

         Development rework is completed. Kindly check and revert back. PFA Latest deliverables & Test result for your ref.

[CP_Print.zip](https://github.com/astpl1998/PPN-Power/files/6625931/CP_Print.zip)

[Test_Result_V1.pdf](https://github.com/astpl1998/PPN-Power/files/6625933/Test_Result_V1.pdf)

Regards,
Naren

**Comment by eafaisal** [comment]
@viki18790 

Kindly do the testing again

**Comment by viki18790** [comment]
@eafaisal 
Please find attached the test result and test case of Testing1
[Testing1_Test_Case_Clearance Permit Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6642026/Testing1_Test_Case_Clearance.Permit.Print.xlsx)
[Testing1_Test Result-Clearance Permit Print.pdf](https://github.com/astpl1998/PPN-Power/files/6642027/Testing1_Test.Result-Clearance.Permit.Print.pdf)

**Comment by eafaisal** [comment]
Testing 2 is completed.

Test Case: [Testing2_Test_Case_Clearance.Permit.Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6654592/Testing2_Test_Case_Clearance.Permit.Print.xlsx)
Test Result: [Testing2_Test.Result-Clearance.Permit.Print.pdf](https://github.com/astpl1998/PPN-Power/files/6654593/Testing2_Test.Result-Clearance.Permit.Print.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@Narendiranath 

The customer asked the following changes in report.

1.	PORTRAIT print format to be changed to LANDSCAPE format.
2.	Work description number of characters to be increased – Description not fully appearing.
3.	Issue Authority column is BLANK. 
4.	Spelling corrections – Scaffolding, ELECTRICAL (in Details of Isolation:)
5.	Total matter to be accommodated in a single page.

The PFS is updated.

[Clearnce.Permits.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6714608/Clearnce.Permits.PFS.v1.1.xlsx)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup 

The customer asked the following changes in report.

1. PORTRAIT print format to be changed to LANDSCAPE format.
2. Work description number of characters to be increased – Description not fully appearing.
3. Issue Authority column is BLANK.
4. Spelling corrections – Scaffolding, ELECTRICAL (in Details of Isolation:)
5. Total matter to be accommodated in a single page.
The PFS is updated.
[Clearnce.Permits.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6719572/Clearnce.Permits.PFS.v1.1.xlsx)

Kindy move to development

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As per the customer requirement we want to do the modification, any clarification needed, Faisal will give the clarification.

**Comment by Narendiranath** [comment]
Hi Faisal,

            Above mentioned points are done. Kindly check & Revert back . Please find Latest deliverable for your ref.

[CP_Print.zip](https://github.com/astpl1998/PPN-Power/files/6748586/CP_Print.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
Test Result: [Testing2_Test_Result_Clearance_Permit.pdf](https://github.com/astpl1998/PPN-Power/files/6776911/Testing2_Test_Result_Clearance_Permit.pdf)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The client requested following alignment changes
1. The clearance permit print should be in single page.
2. The font size and alignment should be same like their current format.

![cp_format](https://user-images.githubusercontent.com/65998153/125621618-e26b3bad-54e5-4cec-883e-1d253828155b.jpeg)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : if they select 2 line item data then it should come in 1 page itself, so align as per that and more than 2 shall go to 2nd page or more.

**Comment by eafaisal** [comment]
Kindly refer the print in attachment.
[CP_print.pdf](https://github.com/astpl1998/PPN-Power/files/6834308/CP_print.pdf)

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Kindly do the allignment work, max 2 multiline should come in single page, if more then that it will move to 2nd page.

**Comment by Narendiranath** [comment]
Hi Faisal,

            Alignment work is completed. Kindly check & Revert back. PFA Latest Test Result for your ref.

[CP_PRint.pdf](https://github.com/astpl1998/PPN-Power/files/6841187/CP_PRint.pdf)

**Comment by eafaisal** [comment]
@Narendiranath 

Client has requested some alignment changes.
Kindly refer the attachment. Client's requirements are marked.
The same are updated in PFS.
Client's print out: 
![CP_Corrections](https://user-images.githubusercontent.com/65998153/126313789-688ff6fc-6395-47f7-888f-c49092146a80.jpeg)
PFS: [Clearnce.Permits.PFS.v1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6847713/Clearnce.Permits.PFS.v1.2.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the alignment for this report as mentioned in comments

**Comment by Narendiranath** [comment]
@eafaisal ,

            Tell me the font name & size. In this report i can only do alignment changes. 

**This below issue is not depends on this report. So don't mention this issue in this report.**

There is an issue while creating Clearance Permit. After creating Clearance Permit, the activity in multi line is vanished.
Ramco is saying that because of the customization (double running series), this issue occurs.
Ramco comment is as follows,
" Dear User,
Due to customization the issue was getting occurred. While creating clearance permit one clearance permit number is generating but in view screen showing different clearance permit number.
Please check the sequence without customization. If it is not working without customization, kindly revert" (R-Track PPNE-114).

**Comment by eafaisal** [comment]
@Narendiranath 

Customer has given the minor alignments.
Kindly check in attachment.

![CP_Changes](https://user-images.githubusercontent.com/65998153/127264294-65f2b9c4-468c-476f-b2c8-334fbfafbaeb.jpg)

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The customer has requested alignment changes.
Kindly move to development.

![CP_Corrections](https://user-images.githubusercontent.com/65998153/128455240-3d213f9e-a257-4761-8314-0fffeb4adaf5.jpeg)

Regards,
Faisal

**Comment by eafaisal** [comment]
@Narendiranath 

The customer accepted the report for deployment.
Thanks.

Regards,
Faisal

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Customer agreed this report. Mail date (06.08.2021)
Kindly move to development to deploy.

PFS: [Clearnce.Permits.PFS.v1.0.xlsx](https://github.com/astpl1998/PPN-Power/files/6948654/Clearnce.Permits.PFS.v1.0.xlsx)
Latest Deliverables: [Deliverable.V.3.zip](https://github.com/astpl1998/PPN-Power/files/6948655/Deliverable.V.3.zip)
Test Case 1: [Testing1_Test_Case_Clearance.Permit.Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6948657/Testing1_Test_Case_Clearance.Permit.Print.xlsx)
Test Result 1: [Testing1_Test.Result-Clearance.Permit.Print.pdf](https://github.com/astpl1998/PPN-Power/files/6948658/Testing1_Test.Result-Clearance.Permit.Print.pdf)
Test Case 2: [Testing2_Test_Case_Clearance.Permit.Print.xlsx](https://github.com/astpl1998/PPN-Power/files/6948659/Testing2_Test_Case_Clearance.Permit.Print.xlsx)
Test Result 2: [Testing2_Test.Result-Clearance.Permit.Print.pdf](https://github.com/astpl1998/PPN-Power/files/6948660/Testing2_Test.Result-Clearance.Permit.Print.pdf)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this development to Live Server

**Comment by karthikeyanamitysoft** [comment]
naren move the  latest deliverables into live server, and attach the same

**Comment by Narendiranath** [comment]
Hi,

 Live server Deployment is completed. Kindly check. PFA Latest Deliverable for your ref.

[PPNE-95.zip](https://github.com/astpl1998/PPN-Power/files/6958993/PPNE-95.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

As per the customer's requirement, the logic for two fields are changed.
1. Remarks
2. Isolation Performed By

The PFS is updated for changes.
[Clearnce.Permits.PFS.v1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6997317/Clearnce.Permits.PFS.v1.1.xlsx)

Kindly move to development.

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the modification in column "Remarks" and "Performed by" in both Test and Live Server

**Comment by karthikeyanamitysoft** [comment]
DEar Naren ,

please do the above mentioned changes from customer.
logic change for remarks and performed by.

REgards,
Karthi

**Comment by Narendiranath** [comment]
Hi Faisal,

                Above mentioned new changes are done. Kindly check. PFA Latest Deliverable for your ref.

[Deliverable V.4.zip](https://github.com/astpl1998/PPN-Power/files/7013685/Deliverable.V.4.zip)

Regards,
Naren

**Comment by eafaisal** [comment]
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket.
